In [6]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [7]:
df = pd.read_csv('강원도_계약종별_전력사용량_월별_12상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 강원도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2012년 01 월 ~ 2012년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201201,강원도,전체(시 / 군 / 구),주택용,"507,057","181,710,905","23,478,724,174",129.2
4,201201,강원도,전체(시 / 군 / 구),일반용,"118,121","393,935,328","43,701,800,435",110.9
...,...,...,...,...,...,...,...,...
907,201206,강원도,횡성군,산업용,512,"11,650,068","1,095,392,298",94
908,201206,강원도,횡성군,심 야,"6,615","5,071,321","235,695,238",46.5
909,201206,강원도,횡성군,일반용,"3,995","7,187,470","782,128,225",108.8
910,201206,강원도,횡성군,주택용,"18,986","4,116,054","441,079,383",107.2
911,201206,강원도,횡성군,합계,"42,581","31,963,793","2,809,437,997",87.9

In [8]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201201,강원도,전체(시 / 군 / 구),주택용,"507,057","181,710,905","23,478,724,174",129.2
4,201201,강원도,전체(시 / 군 / 구),일반용,"118,121","393,935,328","43,701,800,435",110.9
5,201201,강원도,전체(시 / 군 / 구),교육용,"1,540","31,777,612","3,265,573,414",102.8
6,201201,강원도,전체(시 / 군 / 구),산업용,"11,259","581,408,142","55,187,040,829",94.9
...,...,...,...,...,...,...,...,...
907,201206,강원도,횡성군,산업용,512,"11,650,068","1,095,392,298",94
908,201206,강원도,횡성군,심 야,"6,615","5,071,321","235,695,238",46.5
909,201206,강원도,횡성군,일반용,"3,995","7,187,470","782,128,225",108.8
910,201206,강원도,횡성군,주택용,"18,986","4,116,054","441,079,383",107.2
911,201206,강원도,횡성군,합계,"42,581","31,963,793","2,809,437,997",87.9

In [9]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [10]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201201,강원도,전체(시 / 군 / 구),주택용,"507,057","181,710,905","23,478,724,174",129.2
4,201201,강원도,전체(시 / 군 / 구),일반용,"118,121","393,935,328","43,701,800,435",110.9
5,201201,강원도,전체(시 / 군 / 구),교육용,"1,540","31,777,612","3,265,573,414",102.8
6,201201,강원도,전체(시 / 군 / 구),산업용,"11,259","581,408,142","55,187,040,829",94.9
7,201201,강원도,전체(시 / 군 / 구),농사용,"65,193","36,105,700","1,610,830,555",44.6
...,...,...,...,...,...,...,...,...
907,201206,강원도,횡성군,산업용,512,"11,650,068","1,095,392,298",94
908,201206,강원도,횡성군,심 야,"6,615","5,071,321","235,695,238",46.5
909,201206,강원도,횡성군,일반용,"3,995","7,187,470","782,128,225",108.8
910,201206,강원도,횡성군,주택용,"18,986","4,116,054","441,079,383",107.2
911,201206,강원도,횡성군,합계,"42,581","31,963,793","2,809,437,997",87.9

In [11]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201201,강원도,전체(시 / 군 / 구),주택용,"507,057","181,710,905","23,478,724,174",129.2
4,201201,강원도,전체(시 / 군 / 구),일반용,"118,121","393,935,328","43,701,800,435",110.9
5,201201,강원도,전체(시 / 군 / 구),교육용,"1,540","31,777,612","3,265,573,414",102.8
6,201201,강원도,전체(시 / 군 / 구),산업용,"11,259","581,408,142","55,187,040,829",94.9
7,201201,강원도,전체(시 / 군 / 구),농사용,"65,193","36,105,700","1,610,830,555",44.6
8,201201,강원도,전체(시 / 군 / 구),가로등,"88,093","16,284,421","1,462,579,337",89.8
9,201201,강원도,전체(시 / 군 / 구),심 야,"97,060","354,402,984","22,859,854,094",64.5
10,201202,강원도,전체(시 / 군 / 구),주택용,"506,645","183,887,448","24,063,667,910",130.9
11,201202,강원도,전체(시 / 군 / 구),일반용,"118,756","380,390,372","43,491,008,041",114.3
12,201202,강원도,전체(시 / 군 / 구),교육용,"1,541","29,958,084","3,185,361,617",106.3
13,201202,강원도,전체(시 / 군 / 구),산업용,"11,258","537,959,873","53,040,030,542",98.6
14,201202,강원도,전체(시 / 군 / 구),농사용,"65,176","37,079,696","1,651,201,516",44.5
15,201202,강원도,전체(시 / 군 / 구),가로등,"88,331","15,650,134","1,462,281,408",93.4
16,201202,강원도,전체(시 / 군 / 구),심 야,"97,045","361,172,341","23,287,034,141",64.5
17,201203,강원도,전체(시 / 군 / 구),주택용,"507,036","165,417,318","19,326,785,961",116.8
18,201203,강원도,전체(시 / 군 / 구),일반용,"118,828","325,480,053","34,588,423,108",106.3
19,201203,강원도,전체(시 / 군 / 구),교육용,"1,543","29,738,692","2,851,395,594",95.9
20,201203,강원도,전체(시 / 군 / 구),산업용,"11,271","614,494,922","48,282,035,458",78.6
21,201203,강원도,전체(시 / 군 / 구),농사용,"88,005","34,953,679","1,570,654,493",44.9
22,201203,강원도,전체(시 / 군 / 구),가로등,"88,438","14,827,596","1,495,070,728",100.8
23,201203,강원도,전체(시 / 군 / 구),심 야,"97,005","287,015,826","16,502,787,950",57.5
24,201204,강원도,전체(시 / 군 / 구),주택용,"507,443","167,439,497","19,614,726,230",117.1
25,201204,강원도,전체(시 / 군 / 구),일반용,"119,314","298,915,849","29,469,258,321",98.6
26,201204,강원도,전체(시 / 군 / 구),교육용,"1,539","28,387,919","2,503,181,086",88.2
27,201204,강원도,전체(시 / 군 / 구),산업용,"11,282","602,629,232","46,754,679,507",77.6
28,201204,강원도,전체(시 / 군 / 구),농사용,"66,002","32,445,801","1,477,797,471",45.5
29,201204,강원도,전체(시 / 군 / 구),가로등,"88,596","14,660,213","1,443,687,452",98.5
30,201204,강원도,전체(시 / 군 / 구),심 야,"96,880","238,400,841","11,151,120,103",46.8
31,201205,강원도,전체(시 / 군 / 구),주택용,"507,754","152,061,588","16,274,622,866",107.0
32,201205,강원도,전체(시 / 군 / 구),일반용,"119,655","264,209,735","27,324,730,945",103.4
33,201205,강원도,전체(시 / 군 / 구),교육용,"1,531","19,213,284","2,000,127,329",104.1
34,201205,강원도,전체(시 / 군 / 구),산업용,"11,329","623,123,684","49,511,573,284",79.5
35,201205,강원도,전체(시 / 군 / 구),농사용,"66,736","28,290,097","1,320,243,346",46.7
36,201205,강원도,전체(시 / 군 / 구),가로등,"88,868","13,704,971","1,391,950,275",101.6
37,201205,강원도,전체(시 / 군 / 구),심 야,"96,795","129,989,571","6,080,486,596",46.8
38,201206,강원도,전체(시 / 군 / 구),주택용,"508,421","151,143,915","16,084,066,371",106.4
39,201206,강원도,전체(시 / 군 / 구),일반용,"120,075","271,076,322","27,478,361,557",101.4
40,201206,강원도,전체(시 / 군 / 구),교육용,"1,529","18,273,428","1,955,075,758",107.0
41,201206,강원도,전체(시 / 군 / 구),산업용,"11,364","623,503,577","50,719,881,243",81.3
42,201206,강원도,전체(시 / 군 / 구),농사용,"67,743","30,949,460","1,380,413,919",44.6
43,201206,강원도,전체(시 / 군 / 구),가로등,"89,235","13,034,711","1,364,651,233",104.7
44,201206,강원도,전체(시 / 군 / 구),심 야,"96,705","78,388,911","3,678,062,301",46.9
45,합계,합계,합계,합계,"5,367,997","8,413,493,732","745,342,838,498",88.6

In [12]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_11344\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월   시구 계약구분   고객호수(호)      사용량(kWh)
4   201201  강원도  일반용  118,121   393,935,328
11  201202  강원도  일반용  118,756   380,390,372
18  201203  강원도  일반용  118,828   325,480,053
25  201204  강원도  일반용  119,314   298,915,849
32  201205  강원도  일반용  119,655   264,209,735
39  201206  강원도  일반용  120,075   271,076,322

In [13]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [14]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [15]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201201  강원도  강릉시  일반용  15,817   43,600,925
197  201202  강원도  강릉시  일반용  15,908   43,385,435
341  201203  강원도  강릉시  일반용  15,948   39,233,079
485  201204  강원도  강릉시  일반용  16,038   36,768,763
629  201205  강원도  강릉시  일반용  16,047   32,219,716
..      ...  ...  ...  ...      ...          ...
333  201202  강원도  횡성군  일반용   3,972   11,294,392
477  201203  강원도  횡성군  일반용   3,969    9,348,124
621  201204  강원도  횡성군  일반용   3,967    7,937,749
765  201205  강원도  횡성군  일반용   3,984    6,986,071
909  201206  강원도  횡성군  일반용   3,995    7,187,470

[108 rows x 6 columns]

In [16]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'강원도'

In [17]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강릉시',
 '고성군',
 '동해시',
 '삼척시',
 '속초시',
 '양구군',
 '양양군',
 '영월군',
 '원주시',
 '인제군',
 '정선군',
 '철원군',
 '춘천시',
 '태백시',
 '평창군',
 '홍천군',
 '화천군',
 '횡성군']

In [18]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월   시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201201  강원도  강릉시   합계  115,156   178,003,754
199  201202  강원도  강릉시   합계  115,296   175,989,804
343  201203  강원도  강릉시   합계  115,761   174,353,850
487  201204  강원도  강릉시   합계  115,615   170,257,323
631  201205  강원도  강릉시   합계  115,733   158,449,074
..      ...  ...  ...  ...       ...           ...
335  201202  강원도  횡성군   합계   42,192    60,212,523
479  201203  강원도  횡성군   합계   44,220    51,647,191
623  201204  강원도  횡성군   합계   42,339    45,526,205
767  201205  강원도  횡성군   합계   42,409    35,349,184
911  201206  강원도  횡성군   합계   42,581    31,963,793

[108 rows x 6 columns]

In [19]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[178003754, 175989804, 174353850, 170257323, 158449074, 156450067]
[29367707, 29052276, 26275615, 24982298, 20831812, 19502858]
[265327983, 248694513, 271642388, 261592089, 270930538, 264257410]
[110025016, 95866893, 110094634, 109508745, 100725887, 103171165]
[47186422, 46543646, 42256254, 40132761, 34259929, 32603296]
[29412022, 25155428, 21053244, 19307175, 14026481, 12280396]
[29158460, 28794858, 25781145, 24242320, 20090870, 19182620]
[81393107, 78111872, 95202961, 89671779, 86659726, 82624265]
[234121726, 231746051, 204042078, 187197688, 156974037, 153675861]
[37074536, 37410816, 31346491, 28656420, 21769109, 19747437]
[63111930, 61949632, 56994987, 52300090, 46516944, 44246164]
[55194944, 56207617, 46783895, 40998093, 31376637, 29642567]
[162747406, 160109817, 139208333, 131514686, 106415632, 102680503]
[35568031, 35115490, 31561743, 29787962, 26044474, 25036029]
[69331898, 67579089, 54354075, 47137198, 36231106, 32205209]
[80236665, 79539837, 65972287, 58865948, 48202291, 42908502]
[27801707, 28017786, 23356915, 21200572, 15739199, 14192182]
[60561778, 60212523, 51647191, 45526205, 35349184, 31963793]
강원도 지역별 합계 :  [1013503872, 150012566, 1582444921, 629392340, 242982308, 121234746, 147250273, 513663710, 1167757441, 176004809, 325119747, 260203753, 802676377, 183113729, 306838575, 375725530, 130308361, 285260674]
강원도 고객호수 평균:  [19263, 4162, 7370, 7717, 6029, 3220, 4302, 5828, 21692, 4860, 5712, 6325, 20584, 4577, 7210, 9757, 3387, 7109]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [20]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_11344\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201201  강원도  강릉시   합계  115,156   178,003,754
1           201202  강원도  강릉시   합계  115,296   175,989,804
2           201203  강원도  강릉시   합계  115,761   174,353,850
3           201204  강원도  강릉시   합계  115,615   170,257,323
4           201205  강원도  강릉시   합계  115,733   158,449,074
..             ...  ...  ...  ...       ...           ...
121  201201-201206  강원도  태백시   합계      4577     183113729
122  201201-201206  강원도  평창군   합계      7210     306838575
123  201201-201206  강원도  홍천군   합계      9757     375725530
124  201201-201206  강원도  화천군   합계      3387     130308361
125  201201-201206  강원도  횡성군   합계      7109     285260674

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [21]:
Hap = Hap.loc[Hap['년월'] == '201201-201206']
Hap

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201201-201206  강원도  강릉시   합계   19263  1013503872
109  201201-201206  강원도  고성군   합계    4162   150012566
110  201201-201206  강원도  동해시   합계    7370  1582444921
111  201201-201206  강원도  삼척시   합계    7717   629392340
112  201201-201206  강원도  속초시   합계    6029   242982308
113  201201-201206  강원도  양구군   합계    3220   121234746
114  201201-201206  강원도  양양군   합계    4302   147250273
115  201201-201206  강원도  영월군   합계    5828   513663710
116  201201-201206  강원도  원주시   합계   21692  1167757441
117  201201-201206  강원도  인제군   합계    4860   176004809
118  201201-201206  강원도  정선군   합계    5712   325119747
119  201201-201206  강원도  철원군   합계    6325   260203753
120  201201-201206  강원도  춘천시   합계   20584   802676377
121  201201-201206  강원도  태백시   합계    4577   183113729
122  201201-201206  강원도  평창군   합계    7210   306838575
123  201201-201206  강원도  홍천군   합계    9757   375725530
124  201201-201206  강원도  화천군   합계    3387   130308361
125  201201-201206  강원도  횡성군   합계    7109   285260674

In [22]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [24]:
df_3

         년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201201  강원도  강릉시  일반용  15,817   43,600,925
197  201202  강원도  강릉시  일반용  15,908   43,385,435
341  201203  강원도  강릉시  일반용  15,948   39,233,079
485  201204  강원도  강릉시  일반용  16,038   36,768,763
629  201205  강원도  강릉시  일반용  16,047   32,219,716
..      ...  ...  ...  ...      ...          ...
333  201202  강원도  횡성군  일반용   3,972   11,294,392
477  201203  강원도  횡성군  일반용   3,969    9,348,124
621  201204  강원도  횡성군  일반용   3,967    7,937,749
765  201205  강원도  횡성군  일반용   3,984    6,986,071
909  201206  강원도  횡성군  일반용   3,995    7,187,470

[108 rows x 6 columns]

In [25]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [26]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[43600925, 43385435, 39233079, 36768763, 32219716, 32918808]
[10321598, 10112808, 9182568, 8666421, 7963443, 7994798]
[17588274, 17269034, 16595002, 15507581, 13661830, 13694932]
[12958400, 12966068, 11980704, 11087085, 9870580, 10192269]
[22064555, 21487787, 19414970, 18246953, 16545469, 16598473]
[12488428, 7856517, 6590822, 6214791, 4999766, 4908943]
[11110991, 10946835, 10138192, 9482608, 8517002, 8637025]
[7170348, 8418506, 6078471, 5734641, 4980950, 5170951]
[65730589, 64036014, 54229781, 50717748, 44288371, 47598868]
[13620230, 13234638, 11284129, 10496778, 8865249, 8982885]
[21038040, 19892766, 16575619, 13749147, 12829100, 12320239]
[16045708, 15895973, 13300576, 11694772, 9422485, 9871218]
[58051478, 57185649, 48632171, 45854722, 40641338, 43441559]
[10242871, 9768026, 8231391, 7814987, 6749096, 6535071]
[25272437, 22892685, 17428009, 14376547, 13023852, 12847296]
[23650050, 22561627, 18022548, 15993616, 15718670, 15338223]
[11108220, 11185612, 9213897, 8570940, 6926747, 6837294]
[11872186, 11294392, 9348124, 7937749, 6986071, 7187470]
강원도 지역별 일반용 합계 :  [228126726, 54241636, 94316653, 69055106, 114358207, 43059267, 58832653, 37553867, 326601371, 66483909, 96404911, 76230732, 293806917, 49341442, 105840826, 111284734, 53842710, 54625992]
강원도 고객호수 평균:  [15972, 3054, 6051, 5126, 6868, 2084, 3533, 3403, 20552, 3715, 4398, 4315, 17960, 3796, 5041, 6645, 2630, 3973]

In [27]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [28]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [29]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [30]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_11344\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11344\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201201  강원도  강릉시  일반용  15,817   43,600,925
1           201202  강원도  강릉시  일반용  15,908   43,385,435
2           201203  강원도  강릉시  일반용  15,948   39,233,079
3           201204  강원도  강릉시  일반용  16,038   36,768,763
4           201205  강원도  강릉시  일반용  16,047   32,219,716
..             ...  ...  ...  ...      ...          ...
121  201201-201206  강원도  태백시  일반용     3796     49341442
122  201201-201206  강원도  평창군  일반용     5041    105840826
123  201201-201206  강원도  홍천군  일반용     6645    111284734
124  201201-201206  강원도  화천군  일반용     2630     53842710
125  201201-201206  강원도  횡성군  일반용     3973     54625992

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [31]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201201-201206']
GyeonGiHap2

                년월   시구  시군구 계약구분 고객호수(호)   사용량(kWh)
108  201201-201206  강원도  강릉시  일반용   15972  228126726
109  201201-201206  강원도  고성군  일반용    3054   54241636
110  201201-201206  강원도  동해시  일반용    6051   94316653
111  201201-201206  강원도  삼척시  일반용    5126   69055106
112  201201-201206  강원도  속초시  일반용    6868  114358207
113  201201-201206  강원도  양구군  일반용    2084   43059267
114  201201-201206  강원도  양양군  일반용    3533   58832653
115  201201-201206  강원도  영월군  일반용    3403   37553867
116  201201-201206  강원도  원주시  일반용   20552  326601371
117  201201-201206  강원도  인제군  일반용    3715   66483909
118  201201-201206  강원도  정선군  일반용    4398   96404911
119  201201-201206  강원도  철원군  일반용    4315   76230732
120  201201-201206  강원도  춘천시  일반용   17960  293806917
121  201201-201206  강원도  태백시  일반용    3796   49341442
122  201201-201206  강원도  평창군  일반용    5041  105840826
123  201201-201206  강원도  홍천군  일반용    6645  111284734
124  201201-201206  강원도  화천군  일반용    2630   53842710
125  201201-201206  강원도  횡성군  일반용    3973   54625992

In [32]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201201-201206  강원도  강릉시  일반용   15972   228126726
108  201201-201206  강원도  강릉시   합계   19263  1013503872
109  201201-201206  강원도  고성군  일반용    3054    54241636
109  201201-201206  강원도  고성군   합계    4162   150012566
110  201201-201206  강원도  동해시  일반용    6051    94316653
110  201201-201206  강원도  동해시   합계    7370  1582444921
111  201201-201206  강원도  삼척시   합계    7717   629392340
111  201201-201206  강원도  삼척시  일반용    5126    69055106
112  201201-201206  강원도  속초시   합계    6029   242982308
112  201201-201206  강원도  속초시  일반용    6868   114358207
113  201201-201206  강원도  양구군  일반용    2084    43059267
113  201201-201206  강원도  양구군   합계    3220   121234746
114  201201-201206  강원도  양양군   합계    4302   147250273
114  201201-201206  강원도  양양군  일반용    3533    58832653
115  201201-201206  강원도  영월군  일반용    3403    37553867
115  201201-201206  강원도  영월군   합계    5828   513663710
116  201201-201206  강원도  원주시  일반용   20552   326601371
116  201201-201206  강원도  원주시   합계   21692  1167757441
117  201201-201206  강원도  인제군  일반용    3715    66483909
117  201201-201206  강원도  인제군   합계    4860   176004809
118  201201-201206  강원도  정선군   합계    5712   325119747
118  201201-201206  강원도  정선군  일반용    4398    96404911
119  201201-201206  강원도  철원군   합계    6325   260203753
119  201201-201206  강원도  철원군  일반용    4315    76230732
120  201201-201206  강원도  춘천시  일반용   17960   293806917
120  201201-201206  강원도  춘천시   합계   20584   802676377
121  201201-201206  강원도  태백시   합계    4577   183113729
121  201201-201206  강원도  태백시  일반용    3796    49341442
122  201201-201206  강원도  평창군   합계    7210   306838575
122  201201-201206  강원도  평창군  일반용    5041   105840826
123  201201-201206  강원도  홍천군   합계    9757   375725530
123  201201-201206  강원도  홍천군  일반용    6645   111284734
124  201201-201206  강원도  화천군   합계    3387   130308361
124  201201-201206  강원도  화천군  일반용    2630    53842710
125  201201-201206  강원도  횡성군  일반용    3973    54625992
125  201201-201206  강원도  횡성군   합계    7109   285260674

In [33]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[228126726,
 54241636,
 94316653,
 69055106,
 114358207,
 43059267,
 58832653,
 37553867,
 326601371,
 66483909,
 96404911,
 76230732,
 293806917,
 49341442,
 105840826,
 111284734,
 53842710,
 54625992]

In [34]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1013503872,
 150012566,
 1582444921,
 629392340,
 242982308,
 121234746,
 147250273,
 513663710,
 1167757441,
 176004809,
 325119747,
 260203753,
 802676377,
 183113729,
 306838575,
 375725530,
 130308361,
 285260674]

In [35]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[22.51, 36.16, 5.96, 10.97, 47.06, 35.52, 39.95, 7.31, 27.97, 37.77, 29.65, 29.3, 36.6, 26.95, 34.49, 29.62, 41.32, 19.15]

In [36]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    23
1    36
2     6
3    11
4    47
5    36
6    40
7     7
8    28
9    38
10   30
11   29
12   37
13   27
14   34
15   30
16   41
17   19
dtype: float64

In [37]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   강릉시  일반용  23
1   고성군  일반용  36
2   동해시  일반용   6
3   삼척시  일반용  11
4   속초시  일반용  47
5   양구군  일반용  36
6   양양군  일반용  40
7   영월군  일반용   7
8   원주시  일반용  28
9   인제군  일반용  38
10  정선군  일반용  30
11  철원군  일반용  29
12  춘천시  일반용  37
13  태백시  일반용  27
14  평창군  일반용  34
15  홍천군  일반용  30
16  화천군  일반용  41
17  횡성군  일반용  19

In [38]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201201-201206  강원도  강릉시  일반용   15972   228126726  23
1   201201-201206  강원도  강릉시   합계   19263  1013503872 NaN
2   201201-201206  강원도  고성군  일반용    3054    54241636  36
3   201201-201206  강원도  고성군   합계    4162   150012566 NaN
4   201201-201206  강원도  동해시  일반용    6051    94316653   6
5   201201-201206  강원도  동해시   합계    7370  1582444921 NaN
7   201201-201206  강원도  삼척시  일반용    5126    69055106  11
6   201201-201206  강원도  삼척시   합계    7717   629392340 NaN
9   201201-201206  강원도  속초시  일반용    6868   114358207  47
8   201201-201206  강원도  속초시   합계    6029   242982308 NaN
10  201201-201206  강원도  양구군  일반용    2084    43059267  36
11  201201-201206  강원도  양구군   합계    3220   121234746 NaN
13  201201-201206  강원도  양양군  일반용    3533    58832653  40
12  201201-201206  강원도  양양군   합계    4302   147250273 NaN
14  201201-201206  강원도  영월군  일반용    3403    37553867   7
15  201201-201206  강원도  영월군   합계    5828   513663710 NaN
16  201201-201206  강원도  원주시  일반용   20552   326601371  28
17  201201-201206  강원도  원주시   합계   21692  1167757441 NaN
18  201201-201206  강원도  인제군  일반용    3715    66483909  38
19  201201-201206  강원도  인제군   합계    4860   176004809 NaN
21  201201-201206  강원도  정선군  일반용    4398    96404911  30
20  201201-201206  강원도  정선군   합계    5712   325119747 NaN
23  201201-201206  강원도  철원군  일반용    4315    76230732  29
22  201201-201206  강원도  철원군   합계    6325   260203753 NaN
24  201201-201206  강원도  춘천시  일반용   17960   293806917  37
25  201201-201206  강원도  춘천시   합계   20584   802676377 NaN
27  201201-201206  강원도  태백시  일반용    3796    49341442  27
26  201201-201206  강원도  태백시   합계    4577   183113729 NaN
29  201201-201206  강원도  평창군  일반용    5041   105840826  34
28  201201-201206  강원도  평창군   합계    7210   306838575 NaN
31  201201-201206  강원도  홍천군  일반용    6645   111284734  30
30  201201-201206  강원도  홍천군   합계    9757   375725530 NaN
33  201201-201206  강원도  화천군  일반용    2630    53842710  41
32  201201-201206  강원도  화천군   합계    3387   130308361 NaN
34  201201-201206  강원도  횡성군  일반용    3973    54625992  19
35  201201-201206  강원도  횡성군   합계    7109   285260674 NaN

In [39]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [40]:
Final.to_csv("{}_일반용_전력사용량_1201-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [41]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [42]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [43]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [44]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [45]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [46]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [47]:
# SEOUL

In [48]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)