In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경기도_계약종별 전력사용량 월별_14상반기.csv' , encoding='utf-8')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경기도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2014년 01 월 ~ 2014년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,경기도,전체(시 / 군 / 구),주택용,"2,552,869","1,412,764,700","191,435,055,789",135.5
4,201401,경기도,전체(시 / 군 / 구),일반용,"591,665","2,357,902,565","305,050,707,036",129.4
...,...,...,...,...,...,...,...,...
1531,201406,경기도,화성시,산업용,"15,308","942,591,268","106,719,257,234",113.2
1532,201406,경기도,화성시,심 야,"13,413","10,026,710","573,603,392",57.2
1533,201406,경기도,화성시,일반용,"32,444","111,605,659","14,718,374,877",131.9
1534,201406,경기도,화성시,주택용,"96,037","56,454,684","6,973,335,448",123.5
1535,201406,경기도,화성시,합계,"193,211","1,142,354,747","130,767,192,650",114.5

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,경기도,전체(시 / 군 / 구),주택용,"2,552,869","1,412,764,700","191,435,055,789",135.5
4,201401,경기도,전체(시 / 군 / 구),일반용,"591,665","2,357,902,565","305,050,707,036",129.4
5,201401,경기도,전체(시 / 군 / 구),교육용,"4,097","153,436,965","17,520,385,740",114.2
6,201401,경기도,전체(시 / 군 / 구),산업용,"109,861","4,853,126,054","566,504,689,205",116.7
...,...,...,...,...,...,...,...,...
1531,201406,경기도,화성시,산업용,"15,308","942,591,268","106,719,257,234",113.2
1532,201406,경기도,화성시,심 야,"13,413","10,026,710","573,603,392",57.2
1533,201406,경기도,화성시,일반용,"32,444","111,605,659","14,718,374,877",131.9
1534,201406,경기도,화성시,주택용,"96,037","56,454,684","6,973,335,448",123.5
1535,201406,경기도,화성시,합계,"193,211","1,142,354,747","130,767,192,650",114.5

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,경기도,전체(시 / 군 / 구),주택용,"2,552,869","1,412,764,700","191,435,055,789",135.5
4,201401,경기도,전체(시 / 군 / 구),일반용,"591,665","2,357,902,565","305,050,707,036",129.4
5,201401,경기도,전체(시 / 군 / 구),교육용,"4,097","153,436,965","17,520,385,740",114.2
6,201401,경기도,전체(시 / 군 / 구),산업용,"109,861","4,853,126,054","566,504,689,205",116.7
7,201401,경기도,전체(시 / 군 / 구),농사용,"184,365","228,490,681","10,586,663,236",46.3
...,...,...,...,...,...,...,...,...
1531,201406,경기도,화성시,산업용,"15,308","942,591,268","106,719,257,234",113.2
1532,201406,경기도,화성시,심 야,"13,413","10,026,710","573,603,392",57.2
1533,201406,경기도,화성시,일반용,"32,444","111,605,659","14,718,374,877",131.9
1534,201406,경기도,화성시,주택용,"96,037","56,454,684","6,973,335,448",123.5
1535,201406,경기도,화성시,합계,"193,211","1,142,354,747","130,767,192,650",114.5

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,경기도,전체(시 / 군 / 구),주택용,"2,552,869","1,412,764,700","191,435,055,789",135.5
4,201401,경기도,전체(시 / 군 / 구),일반용,"591,665","2,357,902,565","305,050,707,036",129.4
5,201401,경기도,전체(시 / 군 / 구),교육용,"4,097","153,436,965","17,520,385,740",114.2
6,201401,경기도,전체(시 / 군 / 구),산업용,"109,861","4,853,126,054","566,504,689,205",116.7
7,201401,경기도,전체(시 / 군 / 구),농사용,"184,365","228,490,681","10,586,663,236",46.3
8,201401,경기도,전체(시 / 군 / 구),가로등,"283,934","73,182,357","7,850,410,885",107.3
9,201401,경기도,전체(시 / 군 / 구),심 야,"164,888","590,012,498","44,692,879,466",75.7
10,201402,경기도,전체(시 / 군 / 구),주택용,"2,556,983","1,406,048,173","190,364,882,103",135.4
11,201402,경기도,전체(시 / 군 / 구),일반용,"592,465","2,214,675,518","291,324,249,658",131.5
12,201402,경기도,전체(시 / 군 / 구),교육용,"4,144","140,836,681","16,458,538,254",116.9
13,201402,경기도,전체(시 / 군 / 구),산업용,"110,171","4,503,995,388","541,900,519,440",120.3
14,201402,경기도,전체(시 / 군 / 구),농사용,"184,368","222,699,245","10,314,304,122",46.3
15,201402,경기도,전체(시 / 군 / 구),가로등,"284,581","68,973,701","7,715,110,088",111.9
16,201402,경기도,전체(시 / 군 / 구),심 야,"164,642","574,215,375","43,475,478,744",75.7
17,201403,경기도,전체(시 / 군 / 구),주택용,"2,561,467","1,223,578,722","145,507,212,351",118.9
18,201403,경기도,전체(시 / 군 / 구),일반용,"592,551","1,935,800,217","235,114,325,141",121.5
19,201403,경기도,전체(시 / 군 / 구),교육용,"4,137","128,750,311","13,717,104,474",106.5
20,201403,경기도,전체(시 / 군 / 구),산업용,"110,450","4,641,937,852","460,966,612,468",99.3
21,201403,경기도,전체(시 / 군 / 구),농사용,"253,036","179,444,399","8,534,056,914",47.6
22,201403,경기도,전체(시 / 군 / 구),가로등,"284,877","62,642,375","7,113,784,017",113.6
23,201403,경기도,전체(시 / 군 / 구),심 야,"164,435","432,595,918","28,959,462,137",66.9
24,201404,경기도,전체(시 / 군 / 구),주택용,"2,566,446","1,275,524,211","155,907,102,192",122.2
25,201404,경기도,전체(시 / 군 / 구),일반용,"593,939","1,807,326,022","205,865,248,355",113.9
26,201404,경기도,전체(시 / 군 / 구),교육용,"4,151","113,037,290","11,846,672,775",104.8
27,201404,경기도,전체(시 / 군 / 구),산업용,"110,835","4,560,606,849","443,786,614,857",97.3
28,201404,경기도,전체(시 / 군 / 구),농사용,"193,465","158,615,844","7,583,476,585",47.8
29,201404,경기도,전체(시 / 군 / 구),가로등,"286,376","60,879,724","7,157,451,802",117.6
30,201404,경기도,전체(시 / 군 / 구),심 야,"164,125","319,706,237","17,519,821,511",54.8
31,201405,경기도,전체(시 / 군 / 구),주택용,"2,571,321","1,201,940,483","140,626,303,970",117.0
32,201405,경기도,전체(시 / 군 / 구),일반용,"594,742","1,691,083,187","196,098,604,004",116.0
33,201405,경기도,전체(시 / 군 / 구),교육용,"4,156","89,316,139","10,383,404,645",116.3
34,201405,경기도,전체(시 / 군 / 구),산업용,"111,228","4,406,915,234","427,508,343,030",97.0
35,201405,경기도,전체(시 / 군 / 구),농사용,"187,185","150,374,585","6,989,107,336",46.5
36,201405,경기도,전체(시 / 군 / 구),가로등,"291,019","56,950,114","6,910,251,593",121.3
37,201405,경기도,전체(시 / 군 / 구),심 야,"163,698","202,072,555","11,184,088,595",55.3
38,201406,경기도,전체(시 / 군 / 구),주택용,"2,577,653","1,239,412,602","150,989,961,096",121.8
39,201406,경기도,전체(시 / 군 / 구),일반용,"596,219","1,854,205,795","242,633,403,079",130.9
40,201406,경기도,전체(시 / 군 / 구),교육용,"4,158","96,724,067","12,618,671,497",130.5
41,201406,경기도,전체(시 / 군 / 구),산업용,"111,634","4,478,707,366","520,162,023,855",116.1
42,201406,경기도,전체(시 / 군 / 구),농사용,"188,058","149,919,279","7,026,837,356",46.9
43,201406,경기도,전체(시 / 군 / 구),가로등,"291,776","54,280,282","6,786,750,040",125.0
44,201406,경기도,전체(시 / 군 / 구),심 야,"163,251","123,537,218","7,060,266,454",57.2
45,합계,합계,합계,합계,"23,535,421","51,496,244,778","5,741,750,835,895",111.5

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_19776\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월   시구 계약구분   고객호수(호)        사용량(kWh)
4   201401  경기도  일반용  591,665   2,357,902,565
11  201402  경기도  일반용  592,465   2,214,675,518
18  201403  경기도  일반용  592,551   1,935,800,217
25  201404  경기도  일반용  593,939   1,807,326,022
32  201405  경기도  일반용  594,742   1,691,083,187
39  201406  경기도  일반용  596,219   1,854,205,795

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월   시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201401  경기도  가평군  일반용   8,827    27,885,717
301   201402  경기도  가평군  일반용   8,821    26,848,845
549   201403  경기도  가평군  일반용   8,817    22,501,019
797   201404  경기도  가평군  일반용   8,869    19,717,600
1045  201405  경기도  가평군  일반용   8,913    18,251,627
...      ...  ...  ...  ...      ...           ...
541   201402  경기도  화성시  일반용  32,023   132,821,632
789   201403  경기도  화성시  일반용  32,018   120,187,211
1037  201404  경기도  화성시  일반용  32,191   113,025,469
1285  201405  경기도  화성시  일반용  32,255   104,420,608
1533  201406  경기도  화성시  일반용  32,444   111,605,659

[186 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경기도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['가평군',
 '고양시',
 '과천시',
 '광명시',
 '광주시',
 '구리시',
 '군포시',
 '김포시',
 '남양주시',
 '동두천시',
 '부천시',
 '성남시',
 '수원시',
 '시흥시',
 '안산시',
 '안성시',
 '안양시',
 '양주시',
 '양평군',
 '여주시',
 '연천군',
 '오산시',
 '용인시',
 '의왕시',
 '의정부시',
 '이천시',
 '파주시',
 '평택시',
 '포천시',
 '하남시',
 '화성시']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월   시구  시군구 계약구분   고객호수(호)        사용량(kWh)
55    201401  경기도  가평군   합계   56,919      71,399,437
303   201402  경기도  가평군   합계   56,979      68,922,905
551   201403  경기도  가평군   합계   58,080      56,871,863
799   201404  경기도  가평군   합계   57,161      48,908,861
1047  201405  경기도  가평군   합계   57,424      42,181,423
...      ...  ...  ...  ...       ...             ...
543   201402  경기도  화성시   합계  189,896   1,191,438,833
791   201403  경기도  화성시   합계  195,949   1,199,275,129
1039  201404  경기도  화성시   합계  198,276   1,167,390,906
1287  201405  경기도  화성시   합계  192,297   1,119,358,792
1535  201406  경기도  화성시   합계  193,211   1,142,354,747

[186 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[71399437, 68922905, 56871863, 48908861, 42181423, 38682877]
[440912536, 420801930, 366702520, 346593578, 314337588, 321078835]
[37224883, 35205295, 32455015, 30682329, 29356261, 31422963]
[108384250, 103669922, 93710016, 91869224, 86004528, 90636109]
[232173714, 221893903, 192696094, 180993255, 158725960, 161330160]
[69539659, 66524055, 57797329, 55971459, 52343313, 56935284]
[137601609, 130271873, 119604381, 115970846, 108495186, 113147803]
[295245560, 285108476, 253921231, 246717397, 221078615, 223611926]
[272357879, 262176388, 228243303, 217427383, 194439965, 199480815]
[63448555, 60284251, 53617481, 51832536, 46400991, 49403553]
[386365147, 370093264, 337469518, 329034781, 306022669, 327718402]
[429218238, 404343324, 371463735, 355874103, 352069218, 378037297]
[467199908, 445752143, 406077338, 397090830, 377978768, 406570657]
[391303670, 371263757, 353244628, 342227124, 311974485, 321936634]
[742895598, 700384411, 704229403, 686085111, 645533181, 665284571]
[260530495, 248141432, 224260600, 211715580, 188590716, 191920046]
[234666671, 222069899, 200897348, 195117067, 183452613, 195457603]
[208657951, 195483460, 177268029, 170885023, 150270858, 148691725]
[110323773, 107525562, 85705160, 73821319, 59299070, 54755623]
[136303722, 129982724, 114659947, 104791121, 93011874, 90133605]
[57722670, 55658993, 45959273, 42145433, 36952479, 34094206]
[113044597, 106670540, 102078098, 97430771, 91055625, 95596199]
[798144514, 735903157, 715000116, 698147051, 677253011, 688009729]
[64694597, 62606487, 54934338, 53268938, 48752143, 51327340]
[152134195, 144102749, 124679078, 119948880, 112124254, 120717931]
[392959365, 366025569, 361587203, 344234311, 338776705, 341045029]
[697934102, 645025654, 645392339, 623953269, 612824132, 614617784]
[669763362, 626690914, 613082766, 593767041, 571742223, 579656319]
[264958871, 251348966, 224596885, 217259884, 189126476, 180887093]
[101192205, 96073245, 87269630, 84540766, 79119175, 82243744]
[1260614087, 1191438833, 1199275129, 1167390906, 1119358792, 1142354747]
경기도 지역별 합계 :  [326967366, 2210426987, 196346746, 574274049, 1147813086, 359111099, 725091698, 1525683205, 1374125733, 324987367, 2056703781, 2291005915, 2500669644, 2091950298, 4144412275, 1325158869, 1231661201, 1051257046, 491430507, 668882993, 272533054, 605875830, 4312457578, 335583843, 773707087, 2144628182, 3839747280, 3654702625, 1328178175, 530438765, 7080432494]
경기도 고객호수 평균:  [9560, 35232, 2343, 13176, 23512, 8204, 9586, 15726, 26772, 6253, 43893, 45283, 56058, 23488, 46791, 18988, 23412, 12691, 15826, 12811, 6798, 9415, 34102, 5669, 17740, 17942, 23250, 32166, 17303, 7571, 32186]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201401  경기도  가평군   합계  56,919   71,399,437
1           201402  경기도  가평군   합계  56,979   68,922,905
2           201403  경기도  가평군   합계  58,080   56,871,863
3           201404  경기도  가평군   합계  57,161   48,908,861
4           201405  경기도  가평군   합계  57,424   42,181,423
..             ...  ...  ...  ...      ...          ...
212  201401-201406  경기도  파주시   합계    23250   3839747280
213  201401-201406  경기도  평택시   합계    32166   3654702625
214  201401-201406  경기도  포천시   합계    17303   1328178175
215  201401-201406  경기도  하남시   합계     7571    530438765
216  201401-201406  경기도  화성시   합계    32186   7080432494

[217 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201401-201406']
Hap

                년월   시구   시군구 계약구분 고객호수(호)    사용량(kWh)
186  201401-201406  경기도   가평군   합계    9560   326967366
187  201401-201406  경기도   고양시   합계   35232  2210426987
188  201401-201406  경기도   과천시   합계    2343   196346746
189  201401-201406  경기도   광명시   합계   13176   574274049
190  201401-201406  경기도   광주시   합계   23512  1147813086
191  201401-201406  경기도   구리시   합계    8204   359111099
192  201401-201406  경기도   군포시   합계    9586   725091698
193  201401-201406  경기도   김포시   합계   15726  1525683205
194  201401-201406  경기도  남양주시   합계   26772  1374125733
195  201401-201406  경기도  동두천시   합계    6253   324987367
196  201401-201406  경기도   부천시   합계   43893  2056703781
197  201401-201406  경기도   성남시   합계   45283  2291005915
198  201401-201406  경기도   수원시   합계   56058  2500669644
199  201401-201406  경기도   시흥시   합계   23488  2091950298
200  201401-201406  경기도   안산시   합계   46791  4144412275
201  201401-201406  경기도   안성시   합계   18988  1325158869
202  201401-201406  경기도   안양시   합계   23412  1231661201
203  201401-201406  경기도   양주시   합계   12691  1051257046
204  201401-201406  경기도   양평군   합계   15826   491430507
205  201401-201406  경기도   여주시   합계   12811   668882993
206  201401-201406  경기도   연천군   합계    6798   272533054
207  201401-201406  경기도   오산시   합계    9415   605875830
208  201401-201406  경기도   용인시   합계   34102  4312457578
209  201401-201406  경기도   의왕시   합계    5669   335583843
210  201401-201406  경기도  의정부시   합계   17740   773707087
211  201401-201406  경기도   이천시   합계   17942  2144628182
212  201401-201406  경기도   파주시   합계   23250  3839747280
213  201401-201406  경기도   평택시   합계   32166  3654702625
214  201401-201406  경기도   포천시   합계   17303  1328178175
215  201401-201406  경기도   하남시   합계    7571   530438765
216  201401-201406  경기도   화성시   합계   32186  7080432494

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월   시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201401  경기도  가평군  일반용   8,827    27,885,717
301   201402  경기도  가평군  일반용   8,821    26,848,845
549   201403  경기도  가평군  일반용   8,817    22,501,019
797   201404  경기도  가평군  일반용   8,869    19,717,600
1045  201405  경기도  가평군  일반용   8,913    18,251,627
...      ...  ...  ...  ...      ...           ...
541   201402  경기도  화성시  일반용  32,023   132,821,632
789   201403  경기도  화성시  일반용  32,018   120,187,211
1037  201404  경기도  화성시  일반용  32,191   113,025,469
1285  201405  경기도  화성시  일반용  32,255   104,420,608
1533  201406  경기도  화성시  일반용  32,444   111,605,659

[186 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[27885717, 26848845, 22501019, 19717600, 18251627, 18279875]
[183546584, 173186669, 151760366, 142926045, 134506212, 141507693]
[22611436, 21020684, 19668877, 17928741, 17071008, 18355060]
[39755836, 37061294, 32935979, 31519851, 30663908, 32385155]
[55658517, 52859865, 43854753, 40610323, 36244526, 38966332]
[33744598, 31758615, 27044332, 25309557, 23761540, 27247563]
[34750461, 33253586, 28285698, 26792051, 24168521, 26768277]
[54091581, 51230676, 43189963, 39740541, 35680531, 38592066]
[82875556, 79489154, 66795154, 62178960, 55965145, 61066104]
[23589684, 22876497, 19174364, 17895473, 15710649, 18710757]
[123802961, 116460222, 100333523, 94239013, 88262216, 99506996]
[211002162, 195832401, 180023130, 170009009, 168091118, 188322826]
[237717491, 221248199, 201930262, 190671045, 184816646, 206004109]
[68503417, 64445187, 54768083, 51027323, 45792554, 49967032]
[111845502, 105018536, 90536491, 84158260, 76906384, 85019829]
[41788185, 39678352, 34782949, 32318849, 29611944, 31430310]
[105403563, 98865195, 87738703, 81492429, 77502906, 86249048]
[42149203, 39128201, 32941866, 30260595, 27734410, 29473819]
[25413280, 24669319, 20055717, 18362232, 16071307, 16981671]
[27260352, 25944305, 22974929, 21886094, 20648435, 22273159]
[14110174, 13470138, 10860549, 9881799, 8684745, 9134863]
[32455295, 31158121, 26493810, 24821612, 22594428, 24901654]
[195369263, 180250212, 160660012, 149930537, 142697731, 156097228]
[24968831, 23727500, 21084035, 20029522, 18734896, 20308487]
[67033271, 62706598, 53111384, 49512546, 46359988, 53117492]
[55452130, 52323450, 44097102, 39962868, 36926421, 40575050]
[83453629, 79415184, 66099234, 61093271, 55267288, 60462258]
[112365399, 101989432, 88202519, 81244783, 74606547, 83946916]
[46510124, 44439249, 37323613, 34289026, 31143056, 32226284]
[32873315, 31498200, 26384590, 24490598, 22185892, 24722223]
[139915048, 132821632, 120187211, 113025469, 104420608, 111605659]
경기도 지역별 일반용 합계 :  [133484683, 927433569, 116655806, 204322023, 268194316, 168866205, 174018594, 262525358, 408370073, 117957424, 622604931, 1113280646, 1242387752, 334503596, 553485002, 209610589, 537251844, 201688094, 121553526, 140987274, 66142268, 162424920, 985004983, 128853271, 331841279, 269337021, 405790864, 542355596, 225931352, 162154818, 721975627]
경기도 고객호수 평균:  [8871, 38156, 2181, 10845, 22215, 9792, 8408, 17121, 30487, 5925, 34414, 32717, 48777, 21529, 28268, 13362, 24053, 12723, 10806, 8813, 4916, 9476, 34405, 5422, 19763, 14290, 24039, 30519, 17065, 12101, 32125]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19776\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0           201401  경기도  가평군  일반용  8,827   27,885,717
1           201402  경기도  가평군  일반용  8,821   26,848,845
2           201403  경기도  가평군  일반용  8,817   22,501,019
3           201404  경기도  가평군  일반용  8,869   19,717,600
4           201405  경기도  가평군  일반용  8,913   18,251,627
..             ...  ...  ...  ...     ...          ...
212  201401-201406  경기도  파주시  일반용   24039    405790864
213  201401-201406  경기도  평택시  일반용   30519    542355596
214  201401-201406  경기도  포천시  일반용   17065    225931352
215  201401-201406  경기도  하남시  일반용   12101    162154818
216  201401-201406  경기도  화성시  일반용   32125    721975627

[217 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201401-201406']
GyeonGiHap2

                년월   시구   시군구 계약구분 고객호수(호)    사용량(kWh)
186  201401-201406  경기도   가평군  일반용    8871   133484683
187  201401-201406  경기도   고양시  일반용   38156   927433569
188  201401-201406  경기도   과천시  일반용    2181   116655806
189  201401-201406  경기도   광명시  일반용   10845   204322023
190  201401-201406  경기도   광주시  일반용   22215   268194316
191  201401-201406  경기도   구리시  일반용    9792   168866205
192  201401-201406  경기도   군포시  일반용    8408   174018594
193  201401-201406  경기도   김포시  일반용   17121   262525358
194  201401-201406  경기도  남양주시  일반용   30487   408370073
195  201401-201406  경기도  동두천시  일반용    5925   117957424
196  201401-201406  경기도   부천시  일반용   34414   622604931
197  201401-201406  경기도   성남시  일반용   32717  1113280646
198  201401-201406  경기도   수원시  일반용   48777  1242387752
199  201401-201406  경기도   시흥시  일반용   21529   334503596
200  201401-201406  경기도   안산시  일반용   28268   553485002
201  201401-201406  경기도   안성시  일반용   13362   209610589
202  201401-201406  경기도   안양시  일반용   24053   537251844
203  201401-201406  경기도   양주시  일반용   12723   201688094
204  201401-201406  경기도   양평군  일반용   10806   121553526
205  201401-201406  경기도   여주시  일반용    8813   140987274
206  201401-201406  경기도   연천군  일반용    4916    66142268
207  201401-201406  경기도   오산시  일반용    9476   162424920
208  201401-201406  경기도   용인시  일반용   34405   985004983
209  201401-201406  경기도   의왕시  일반용    5422   128853271
210  201401-201406  경기도  의정부시  일반용   19763   331841279
211  201401-201406  경기도   이천시  일반용   14290   269337021
212  201401-201406  경기도   파주시  일반용   24039   405790864
213  201401-201406  경기도   평택시  일반용   30519   542355596
214  201401-201406  경기도   포천시  일반용   17065   225931352
215  201401-201406  경기도   하남시  일반용   12101   162154818
216  201401-201406  경기도   화성시  일반용   32125   721975627

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
186  201401-201406  경기도  가평군  일반용    8871   133484683
186  201401-201406  경기도  가평군   합계    9560   326967366
187  201401-201406  경기도  고양시  일반용   38156   927433569
187  201401-201406  경기도  고양시   합계   35232  2210426987
188  201401-201406  경기도  과천시  일반용    2181   116655806
..             ...  ...  ...  ...     ...         ...
214  201401-201406  경기도  포천시  일반용   17065   225931352
215  201401-201406  경기도  하남시   합계    7571   530438765
215  201401-201406  경기도  하남시  일반용   12101   162154818
216  201401-201406  경기도  화성시  일반용   32125   721975627
216  201401-201406  경기도  화성시   합계   32186  7080432494

[62 rows x 6 columns]

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[133484683,
 927433569,
 116655806,
 204322023,
 268194316,
 168866205,
 174018594,
 262525358,
 408370073,
 117957424,
 622604931,
 1113280646,
 1242387752,
 334503596,
 553485002,
 209610589,
 537251844,
 201688094,
 121553526,
 140987274,
 66142268,
 162424920,
 985004983,
 128853271,
 331841279,
 269337021,
 405790864,
 542355596,
 225931352,
 162154818,
 721975627]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[326967366,
 2210426987,
 196346746,
 574274049,
 1147813086,
 359111099,
 725091698,
 1525683205,
 1374125733,
 324987367,
 2056703781,
 2291005915,
 2500669644,
 2091950298,
 4144412275,
 1325158869,
 1231661201,
 1051257046,
 491430507,
 668882993,
 272533054,
 605875830,
 4312457578,
 335583843,
 773707087,
 2144628182,
 3839747280,
 3654702625,
 1328178175,
 530438765,
 7080432494]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[40.83, 41.96, 59.41, 35.58, 23.37, 47.02, 24.0, 17.21, 29.72, 36.3, 30.27, 48.59, 49.68, 15.99, 13.35, 15.82, 43.62, 19.19, 24.73, 21.08, 24.27, 26.81, 22.84, 38.4, 42.89, 12.56, 10.57, 14.84, 17.01, 30.57, 10.2]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    41
1    42
2    59
3    36
4    23
5    47
6    24
7    17
8    30
9    36
10   30
11   49
12   50
13   16
14   13
15   16
16   44
17   19
18   25
19   21
20   24
21   27
22   23
23   38
24   43
25   13
26   11
27   15
28   17
29   31
30   10
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

     시군구 계약구분  비율
0    가평군  일반용  41
1    고양시  일반용  42
2    과천시  일반용  59
3    광명시  일반용  36
4    광주시  일반용  23
5    구리시  일반용  47
6    군포시  일반용  24
7    김포시  일반용  17
8   남양주시  일반용  30
9   동두천시  일반용  36
10   부천시  일반용  30
11   성남시  일반용  49
12   수원시  일반용  50
13   시흥시  일반용  16
14   안산시  일반용  13
15   안성시  일반용  16
16   안양시  일반용  44
17   양주시  일반용  19
18   양평군  일반용  25
19   여주시  일반용  21
20   연천군  일반용  24
21   오산시  일반용  27
22   용인시  일반용  23
23   의왕시  일반용  38
24  의정부시  일반용  43
25   이천시  일반용  13
26   파주시  일반용  11
27   평택시  일반용  15
28   포천시  일반용  17
29   하남시  일반용  31
30   화성시  일반용  10

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201401-201406  경기도  가평군  일반용    8871   133484683  41
1   201401-201406  경기도  가평군   합계    9560   326967366 NaN
2   201401-201406  경기도  고양시  일반용   38156   927433569  42
3   201401-201406  경기도  고양시   합계   35232  2210426987 NaN
4   201401-201406  경기도  과천시  일반용    2181   116655806  59
..            ...  ...  ...  ...     ...         ...  ..
56  201401-201406  경기도  포천시   합계   17303  1328178175 NaN
59  201401-201406  경기도  하남시  일반용   12101   162154818  31
58  201401-201406  경기도  하남시   합계    7571   530438765 NaN
60  201401-201406  경기도  화성시  일반용   32125   721975627  10
61  201401-201406  경기도  화성시   합계   32186  7080432494 NaN

[62 rows x 7 columns]

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1401-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)