In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경기도_계약종별 전력사용량 월별_14하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경기도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2014년 07 월 ~ 2014년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,경기도,전체(시 / 군 / 구),주택용,"2,585,546","1,275,518,251","161,892,525,967",126.9
4,201407,경기도,전체(시 / 군 / 구),일반용,"597,452","2,080,442,262","301,649,852,224",145.0
...,...,...,...,...,...,...,...,...
1531,201412,경기도,화성시,산업용,"15,791","1,042,268,327","121,575,855,670",116.6
1532,201412,경기도,화성시,심 야,"13,343","33,504,343","2,536,391,017",75.7
1533,201412,경기도,화성시,일반용,"33,497","134,596,137","18,104,137,479",134.5
1534,201412,경기도,화성시,주택용,"99,766","63,016,707","8,168,342,420",129.6
1535,201412,경기도,화성시,합계,"206,136","1,310,520,884","152,928,912,840",116.7

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,경기도,전체(시 / 군 / 구),주택용,"2,585,546","1,275,518,251","161,892,525,967",126.9
4,201407,경기도,전체(시 / 군 / 구),일반용,"597,452","2,080,442,262","301,649,852,224",145.0
5,201407,경기도,전체(시 / 군 / 구),교육용,"4,159","114,127,377","15,545,791,201",136.2
6,201407,경기도,전체(시 / 군 / 구),산업용,"112,008","4,764,338,908","591,243,221,300",124.1
...,...,...,...,...,...,...,...,...
1531,201412,경기도,화성시,산업용,"15,791","1,042,268,327","121,575,855,670",116.6
1532,201412,경기도,화성시,심 야,"13,343","33,504,343","2,536,391,017",75.7
1533,201412,경기도,화성시,일반용,"33,497","134,596,137","18,104,137,479",134.5
1534,201412,경기도,화성시,주택용,"99,766","63,016,707","8,168,342,420",129.6
1535,201412,경기도,화성시,합계,"206,136","1,310,520,884","152,928,912,840",116.7

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,경기도,전체(시 / 군 / 구),주택용,"2,585,546","1,275,518,251","161,892,525,967",126.9
4,201407,경기도,전체(시 / 군 / 구),일반용,"597,452","2,080,442,262","301,649,852,224",145.0
5,201407,경기도,전체(시 / 군 / 구),교육용,"4,159","114,127,377","15,545,791,201",136.2
6,201407,경기도,전체(시 / 군 / 구),산업용,"112,008","4,764,338,908","591,243,221,300",124.1
7,201407,경기도,전체(시 / 군 / 구),농사용,"188,896","150,764,406","7,236,584,295",48.0
...,...,...,...,...,...,...,...,...
1531,201412,경기도,화성시,산업용,"15,791","1,042,268,327","121,575,855,670",116.6
1532,201412,경기도,화성시,심 야,"13,343","33,504,343","2,536,391,017",75.7
1533,201412,경기도,화성시,일반용,"33,497","134,596,137","18,104,137,479",134.5
1534,201412,경기도,화성시,주택용,"99,766","63,016,707","8,168,342,420",129.6
1535,201412,경기도,화성시,합계,"206,136","1,310,520,884","152,928,912,840",116.7

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,경기도,전체(시 / 군 / 구),주택용,"2,585,546","1,275,518,251","161,892,525,967",126.9
4,201407,경기도,전체(시 / 군 / 구),일반용,"597,452","2,080,442,262","301,649,852,224",145.0
5,201407,경기도,전체(시 / 군 / 구),교육용,"4,159","114,127,377","15,545,791,201",136.2
6,201407,경기도,전체(시 / 군 / 구),산업용,"112,008","4,764,338,908","591,243,221,300",124.1
7,201407,경기도,전체(시 / 군 / 구),농사용,"188,896","150,764,406","7,236,584,295",48.0
8,201407,경기도,전체(시 / 군 / 구),가로등,"292,871","53,170,104","6,620,037,534",124.5
9,201407,경기도,전체(시 / 군 / 구),심 야,"162,811","91,509,678","5,476,955,987",59.9
10,201408,경기도,전체(시 / 군 / 구),주택용,"2,593,354","1,412,867,359","197,173,377,369",139.6
11,201408,경기도,전체(시 / 군 / 구),일반용,"598,532","2,204,496,976","311,937,865,236",141.5
12,201408,경기도,전체(시 / 군 / 구),교육용,"4,161","99,371,086","14,091,488,569",141.8
13,201408,경기도,전체(시 / 군 / 구),산업용,"112,301","4,573,833,126","556,977,226,391",121.8
14,201408,경기도,전체(시 / 군 / 구),농사용,"189,812","172,177,591","8,291,428,851",48.2
15,201408,경기도,전체(시 / 군 / 구),가로등,"293,819","56,209,083","6,778,383,952",120.6
16,201408,경기도,전체(시 / 군 / 구),심 야,"162,435","85,725,032","5,162,281,601",60.2
17,201409,경기도,전체(시 / 군 / 구),주택용,"2,600,409","1,294,758,371","163,377,279,618",126.2
18,201409,경기도,전체(시 / 군 / 구),일반용,"599,403","1,975,415,416","248,311,440,642",125.7
19,201409,경기도,전체(시 / 군 / 구),교육용,"4,172","102,596,004","12,267,284,453",119.6
20,201409,경기도,전체(시 / 군 / 구),산업용,"112,605","4,383,642,203","446,385,920,964",101.8
21,201409,경기도,전체(시 / 군 / 구),농사용,"190,502","171,489,874","8,218,162,343",47.9
22,201409,경기도,전체(시 / 군 / 구),가로등,"294,271","60,369,921","7,049,916,409",116.8
23,201409,경기도,전체(시 / 군 / 구),심 야,"162,248","87,520,730","5,206,894,665",59.5
24,201410,경기도,전체(시 / 군 / 구),주택용,"2,607,191","1,196,046,466","138,750,771,141",116.0
25,201410,경기도,전체(시 / 군 / 구),일반용,"600,195","1,754,051,447","202,412,125,448",115.4
26,201410,경기도,전체(시 / 군 / 구),교육용,"4,176","92,013,867","10,299,158,817",111.9
27,201410,경기도,전체(시 / 군 / 구),산업용,"112,862","4,482,410,114","436,568,294,781",97.4
28,201410,경기도,전체(시 / 군 / 구),농사용,"190,877","145,948,590","7,249,515,936",49.7
29,201410,경기도,전체(시 / 군 / 구),가로등,"294,684","65,199,206","7,286,991,286",111.8
30,201410,경기도,전체(시 / 군 / 구),심 야,"162,171","124,563,069","7,092,599,728",56.9
31,201411,경기도,전체(시 / 군 / 구),주택용,"2,614,120","1,280,076,742","157,555,086,465",123.1
32,201411,경기도,전체(시 / 군 / 구),일반용,"602,097","1,812,010,889","235,168,994,598",129.8
33,201411,경기도,전체(시 / 군 / 구),교육용,"4,180","106,800,227","12,744,125,992",119.3
34,201411,경기도,전체(시 / 군 / 구),산업용,"113,170","4,511,645,424","523,040,675,073",115.9
35,201411,경기도,전체(시 / 군 / 구),농사용,"259,722","226,325,818","9,570,002,160",42.3
36,201411,경기도,전체(시 / 군 / 구),가로등,"295,391","71,092,232","7,749,151,835",109.0
37,201411,경기도,전체(시 / 군 / 구),심 야,"162,132","272,597,479","17,530,667,868",64.3
38,201412,경기도,전체(시 / 군 / 구),주택용,"2,619,077","1,346,116,382","172,563,168,763",128.2
39,201412,경기도,전체(시 / 군 / 구),일반용,"605,026","2,206,976,057","296,463,637,770",134.3
40,201412,경기도,전체(시 / 군 / 구),교육용,"4,191","164,792,096","18,464,211,794",112.0
41,201412,경기도,전체(시 / 군 / 구),산업용,"113,420","4,889,142,756","582,693,971,390",119.2
42,201412,경기도,전체(시 / 군 / 구),농사용,"198,530","207,677,874","9,803,676,448",47.2
43,201412,경기도,전체(시 / 군 / 구),가로등,"296,124","73,300,790","7,835,020,587",106.9
44,201412,경기도,전체(시 / 군 / 구),심 야,"162,090","445,330,392","33,733,171,646",75.7
45,합계,합계,합계,합계,"23,883,193","50,684,461,675","5,975,468,939,097",117.9

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_17848\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월   시구 계약구분   고객호수(호)        사용량(kWh)
4   201407  경기도  일반용  597,452   2,080,442,262
11  201408  경기도  일반용  598,532   2,204,496,976
18  201409  경기도  일반용  599,403   1,975,415,416
25  201410  경기도  일반용  600,195   1,754,051,447
32  201411  경기도  일반용  602,097   1,812,010,889
39  201412  경기도  일반용  605,026   2,206,976,057

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월   시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201407  경기도  가평군  일반용   9,038    19,980,883
301   201408  경기도  가평군  일반용   9,064    22,927,474
549   201409  경기도  가평군  일반용   9,093    19,931,816
797   201410  경기도  가평군  일반용   9,128    17,924,570
1045  201411  경기도  가평군  일반용   9,112    20,987,713
...      ...  ...  ...  ...      ...           ...
541   201408  경기도  화성시  일반용  32,782   127,874,103
789   201409  경기도  화성시  일반용  32,914   116,042,070
1037  201410  경기도  화성시  일반용  33,065   107,257,254
1285  201411  경기도  화성시  일반용  33,242   111,455,619
1533  201412  경기도  화성시  일반용  33,497   134,596,137

[186 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경기도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['가평군',
 '고양시',
 '과천시',
 '광명시',
 '광주시',
 '구리시',
 '군포시',
 '김포시',
 '남양주시',
 '동두천시',
 '부천시',
 '성남시',
 '수원시',
 '시흥시',
 '안산시',
 '안성시',
 '안양시',
 '양주시',
 '양평군',
 '여주시',
 '연천군',
 '오산시',
 '용인시',
 '의왕시',
 '의정부시',
 '이천시',
 '파주시',
 '평택시',
 '포천시',
 '하남시',
 '화성시']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월   시구  시군구 계약구분   고객호수(호)        사용량(kWh)
55    201407  경기도  가평군   합계   57,891      39,417,230
303   201408  경기도  가평군   합계   58,107      43,812,302
551   201409  경기도  가평군   합계   58,327      40,889,904
799   201410  경기도  가평군   합계   58,457      40,120,173
1047  201411  경기도  가평군   합계   59,630      51,149,374
...      ...  ...  ...  ...       ...             ...
543   201408  경기도  화성시   합계  195,427   1,194,624,576
791   201409  경기도  화성시   합계  196,422   1,135,561,047
1039  201410  경기도  화성시   합계  197,314   1,135,644,881
1287  201411  경기도  화성시   합계  204,094   1,182,954,437
1535  201412  경기도  화성시   합계  206,136   1,310,520,884

[186 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[39417230, 43812302, 40889904, 40120173, 51149374, 61995084]
[346545191, 373015939, 339647978, 316535542, 341493784, 405468046]
[34470174, 35803781, 31875444, 29147060, 30007235, 34180702]
[100984804, 101117241, 92189141, 85524974, 91589552, 104282557]
[166879209, 172454249, 162003887, 159392729, 183324928, 215265646]
[61866033, 65872639, 59296429, 53420494, 56168162, 64948564]
[121821607, 123866453, 116523290, 109680221, 112322055, 131580029]
[233112826, 232388757, 220571725, 223329521, 249203991, 288978928]
[208087271, 220088000, 205074431, 196014067, 217448936, 252513957]
[52746072, 54523520, 51275726, 49884863, 52967976, 65041781]
[355759566, 362645071, 336525557, 310917002, 318576370, 365641198]
[421203619, 434309655, 390668508, 355726344, 364117114, 420837321]
[443595921, 461081097, 424285598, 388958965, 396915986, 454224581]
[341231239, 330363335, 318436077, 317180588, 327780387, 372763380]
[724040164, 706721062, 666249681, 669042344, 654964872, 720389710]
[207311294, 206824680, 196213722, 191927998, 215152463, 242735316]
[213026164, 221404263, 202650007, 185392199, 190955183, 221335106]
[152334486, 152091677, 147885023, 152409766, 174839379, 195307448]
[52730823, 56655564, 53387052, 54153986, 78487857, 94388391]
[91805690, 92882452, 89605289, 89407661, 112215963, 123324765]
[33441394, 35886565, 34151684, 34081072, 44827897, 50240295]
[102587677, 105892977, 96806396, 93278399, 95867366, 106487770]
[722838406, 735280909, 687832429, 671185193, 697333593, 773500444]
[54517216, 56626463, 51961509, 48658830, 52276037, 60546608]
[130317301, 137633813, 125237389, 113153986, 120957806, 143187029]
[362931468, 369757715, 346732771, 343343366, 365126432, 392224200]
[647362251, 658235968, 622908842, 614591906, 631713028, 681050526]
[613301887, 592518900, 568393126, 572024346, 576423513, 645335467]
[180864107, 179550104, 175895700, 176168431, 208811902, 236704217]
[87974658, 90750526, 85057157, 79935852, 84575233, 98336397]
[1224765238, 1194624576, 1135561047, 1135644881, 1182954437, 1310520884]
경기도 지역별 합계 :  [277384067, 2122706480, 195484396, 575688269, 1059320648, 361572321, 715793655, 1447585748, 1299226662, 326439938, 2050064764, 2386862561, 2569062148, 2007755006, 4141407833, 1260165473, 1234762922, 974867779, 389803673, 599241820, 232628907, 600920585, 4287970974, 324586663, 770487324, 2180115952, 3855862521, 3567997239, 1157994461, 526629823, 7184071063]
경기도 고객호수 평균:  [9753, 35607, 2372, 13264, 24177, 8252, 9720, 16066, 27197, 6308, 44201, 45445, 56689, 23770, 47266, 19236, 23595, 12831, 16190, 13008, 6884, 9580, 34791, 5711, 18010, 18653, 23554, 32917, 17567, 7637, 33157]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201407  경기도  가평군   합계  57,891   39,417,230
1           201408  경기도  가평군   합계  58,107   43,812,302
2           201409  경기도  가평군   합계  58,327   40,889,904
3           201410  경기도  가평군   합계  58,457   40,120,173
4           201411  경기도  가평군   합계  59,630   51,149,374
..             ...  ...  ...  ...      ...          ...
212  201407-201412  경기도  파주시   합계    23554   3855862521
213  201407-201412  경기도  평택시   합계    32917   3567997239
214  201407-201412  경기도  포천시   합계    17567   1157994461
215  201407-201412  경기도  하남시   합계     7637    526629823
216  201407-201412  경기도  화성시   합계    33157   7184071063

[217 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201407-201412']
Hap

                년월   시구   시군구 계약구분 고객호수(호)    사용량(kWh)
186  201407-201412  경기도   가평군   합계    9753   277384067
187  201407-201412  경기도   고양시   합계   35607  2122706480
188  201407-201412  경기도   과천시   합계    2372   195484396
189  201407-201412  경기도   광명시   합계   13264   575688269
190  201407-201412  경기도   광주시   합계   24177  1059320648
191  201407-201412  경기도   구리시   합계    8252   361572321
192  201407-201412  경기도   군포시   합계    9720   715793655
193  201407-201412  경기도   김포시   합계   16066  1447585748
194  201407-201412  경기도  남양주시   합계   27197  1299226662
195  201407-201412  경기도  동두천시   합계    6308   326439938
196  201407-201412  경기도   부천시   합계   44201  2050064764
197  201407-201412  경기도   성남시   합계   45445  2386862561
198  201407-201412  경기도   수원시   합계   56689  2569062148
199  201407-201412  경기도   시흥시   합계   23770  2007755006
200  201407-201412  경기도   안산시   합계   47266  4141407833
201  201407-201412  경기도   안성시   합계   19236  1260165473
202  201407-201412  경기도   안양시   합계   23595  1234762922
203  201407-201412  경기도   양주시   합계   12831   974867779
204  201407-201412  경기도   양평군   합계   16190   389803673
205  201407-201412  경기도   여주시   합계   13008   599241820
206  201407-201412  경기도   연천군   합계    6884   232628907
207  201407-201412  경기도   오산시   합계    9580   600920585
208  201407-201412  경기도   용인시   합계   34791  4287970974
209  201407-201412  경기도   의왕시   합계    5711   324586663
210  201407-201412  경기도  의정부시   합계   18010   770487324
211  201407-201412  경기도   이천시   합계   18653  2180115952
212  201407-201412  경기도   파주시   합계   23554  3855862521
213  201407-201412  경기도   평택시   합계   32917  3567997239
214  201407-201412  경기도   포천시   합계   17567  1157994461
215  201407-201412  경기도   하남시   합계    7637   526629823
216  201407-201412  경기도   화성시   합계   33157  7184071063

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월   시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201407  경기도  가평군  일반용   9,038    19,980,883
301   201408  경기도  가평군  일반용   9,064    22,927,474
549   201409  경기도  가평군  일반용   9,093    19,931,816
797   201410  경기도  가평군  일반용   9,128    17,924,570
1045  201411  경기도  가평군  일반용   9,112    20,987,713
...      ...  ...  ...  ...      ...           ...
541   201408  경기도  화성시  일반용  32,782   127,874,103
789   201409  경기도  화성시  일반용  32,914   116,042,070
1037  201410  경기도  화성시  일반용  33,065   107,257,254
1285  201411  경기도  화성시  일반용  33,242   111,455,619
1533  201412  경기도  화성시  일반용  33,497   134,596,137

[186 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[19980883, 22927474, 19931816, 17924570, 20987713, 25091420]
[158363717, 171289967, 153495488, 140522717, 142803100, 170178963]
[20181696, 20929060, 18553734, 16905557, 17113592, 20171313]
[37405252, 39242451, 34815812, 32664102, 31523862, 37348135]
[43027041, 46653970, 42056846, 37946340, 41507656, 52013053]
[30926020, 33096320, 29258398, 24896411, 25903955, 31381612]
[30319661, 36046145, 32833076, 28651899, 28510703, 34416671]
[43966551, 47288978, 42960388, 38192038, 40725633, 52887183]
[66813563, 72797144, 65222651, 57313234, 61501290, 74661793]
[20247451, 22395713, 20526110, 15693604, 16334707, 19657592]
[112914260, 119984517, 108349240, 92194403, 91382705, 112228927]
[215220704, 220550979, 195853255, 173302057, 173330976, 208733837]
[233198987, 241571131, 214996196, 192522102, 192304690, 231828705]
[56362657, 60764928, 54772323, 47624643, 49980702, 62943829]
[96553789, 104105528, 92860393, 79827156, 80909082, 100602019]
[34888964, 36221221, 33189396, 29904426, 32054115, 38758756]
[97993431, 103214860, 92882223, 81196070, 81213252, 98797175]
[32504490, 34284848, 30527589, 27922674, 31309721, 38994048]
[18067097, 20501392, 17967181, 16217420, 18932116, 22885556]
[24368213, 25255636, 22691437, 20866079, 22450524, 26194621]
[9972776, 10889884, 9747124, 8972148, 10531986, 13267769]
[27930487, 30307233, 27204318, 23808566, 23926610, 29285662]
[172642900, 179619337, 160827026, 145298361, 150267319, 182836900]
[22467233, 23509672, 20863922, 18705513, 19129695, 23277506]
[59653436, 63573349, 56483173, 47904986, 50090491, 61781506]
[45485324, 48028074, 42740541, 38371658, 42046221, 53002922]
[67193568, 73435319, 65966188, 57577101, 61718514, 75680900]
[94456913, 100560577, 90942952, 79451387, 82371008, 99333966]
[34551578, 38165904, 34447220, 31195565, 34518663, 42223730]
[27538613, 29411262, 26407330, 23221406, 25174669, 31913851]
[125245007, 127874103, 116042070, 107257254, 111455619, 134596137]
경기도 지역별 일반용 합계 :  [126843876, 936653952, 113854952, 212999614, 263204906, 175462716, 190778155, 266020771, 398309675, 114855177, 637054052, 1186991808, 1306421811, 332449082, 554857967, 205016878, 555297011, 195543370, 114570762, 141826510, 63381687, 162462876, 991491843, 127953541, 339486941, 269674740, 401571590, 547116803, 215102660, 163667131, 722470190]
경기도 고객호수 평균:  [9105, 38499, 2211, 10955, 22548, 9785, 8526, 17640, 31022, 5962, 34372, 32846, 49383, 21619, 28412, 13492, 24085, 12815, 11080, 8929, 4942, 9601, 34980, 5449, 19937, 14475, 24161, 31151, 17202, 12233, 33022]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17848\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0           201407  경기도  가평군  일반용  9,038   19,980,883
1           201408  경기도  가평군  일반용  9,064   22,927,474
2           201409  경기도  가평군  일반용  9,093   19,931,816
3           201410  경기도  가평군  일반용  9,128   17,924,570
4           201411  경기도  가평군  일반용  9,112   20,987,713
..             ...  ...  ...  ...     ...          ...
212  201407-201412  경기도  파주시  일반용   24161    401571590
213  201407-201412  경기도  평택시  일반용   31151    547116803
214  201407-201412  경기도  포천시  일반용   17202    215102660
215  201407-201412  경기도  하남시  일반용   12233    163667131
216  201407-201412  경기도  화성시  일반용   33022    722470190

[217 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201407-201412']
GyeonGiHap2

                년월   시구   시군구 계약구분 고객호수(호)    사용량(kWh)
186  201407-201412  경기도   가평군  일반용    9105   126843876
187  201407-201412  경기도   고양시  일반용   38499   936653952
188  201407-201412  경기도   과천시  일반용    2211   113854952
189  201407-201412  경기도   광명시  일반용   10955   212999614
190  201407-201412  경기도   광주시  일반용   22548   263204906
191  201407-201412  경기도   구리시  일반용    9785   175462716
192  201407-201412  경기도   군포시  일반용    8526   190778155
193  201407-201412  경기도   김포시  일반용   17640   266020771
194  201407-201412  경기도  남양주시  일반용   31022   398309675
195  201407-201412  경기도  동두천시  일반용    5962   114855177
196  201407-201412  경기도   부천시  일반용   34372   637054052
197  201407-201412  경기도   성남시  일반용   32846  1186991808
198  201407-201412  경기도   수원시  일반용   49383  1306421811
199  201407-201412  경기도   시흥시  일반용   21619   332449082
200  201407-201412  경기도   안산시  일반용   28412   554857967
201  201407-201412  경기도   안성시  일반용   13492   205016878
202  201407-201412  경기도   안양시  일반용   24085   555297011
203  201407-201412  경기도   양주시  일반용   12815   195543370
204  201407-201412  경기도   양평군  일반용   11080   114570762
205  201407-201412  경기도   여주시  일반용    8929   141826510
206  201407-201412  경기도   연천군  일반용    4942    63381687
207  201407-201412  경기도   오산시  일반용    9601   162462876
208  201407-201412  경기도   용인시  일반용   34980   991491843
209  201407-201412  경기도   의왕시  일반용    5449   127953541
210  201407-201412  경기도  의정부시  일반용   19937   339486941
211  201407-201412  경기도   이천시  일반용   14475   269674740
212  201407-201412  경기도   파주시  일반용   24161   401571590
213  201407-201412  경기도   평택시  일반용   31151   547116803
214  201407-201412  경기도   포천시  일반용   17202   215102660
215  201407-201412  경기도   하남시  일반용   12233   163667131
216  201407-201412  경기도   화성시  일반용   33022   722470190

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
186  201407-201412  경기도  가평군  일반용    9105   126843876
186  201407-201412  경기도  가평군   합계    9753   277384067
187  201407-201412  경기도  고양시  일반용   38499   936653952
187  201407-201412  경기도  고양시   합계   35607  2122706480
188  201407-201412  경기도  과천시  일반용    2211   113854952
..             ...  ...  ...  ...     ...         ...
214  201407-201412  경기도  포천시  일반용   17202   215102660
215  201407-201412  경기도  하남시   합계    7637   526629823
215  201407-201412  경기도  하남시  일반용   12233   163667131
216  201407-201412  경기도  화성시  일반용   33022   722470190
216  201407-201412  경기도  화성시   합계   33157  7184071063

[62 rows x 6 columns]

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[126843876,
 936653952,
 113854952,
 212999614,
 263204906,
 175462716,
 190778155,
 266020771,
 398309675,
 114855177,
 637054052,
 1186991808,
 1306421811,
 332449082,
 554857967,
 205016878,
 555297011,
 195543370,
 114570762,
 141826510,
 63381687,
 162462876,
 991491843,
 127953541,
 339486941,
 269674740,
 401571590,
 547116803,
 215102660,
 163667131,
 722470190]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[277384067,
 2122706480,
 195484396,
 575688269,
 1059320648,
 361572321,
 715793655,
 1447585748,
 1299226662,
 326439938,
 2050064764,
 2386862561,
 2569062148,
 2007755006,
 4141407833,
 1260165473,
 1234762922,
 974867779,
 389803673,
 599241820,
 232628907,
 600920585,
 4287970974,
 324586663,
 770487324,
 2180115952,
 3855862521,
 3567997239,
 1157994461,
 526629823,
 7184071063]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[45.73, 44.13, 58.24, 37.0, 24.85, 48.53, 26.65, 18.38, 30.66, 35.18, 31.07, 49.73, 50.85, 16.56, 13.4, 16.27, 44.97, 20.06, 29.39, 23.67, 27.25, 27.04, 23.12, 39.42, 44.06, 12.37, 10.41, 15.33, 18.58, 31.08, 10.06]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    46
1    44
2    58
3    37
4    25
5    49
6    27
7    18
8    31
9    35
10   31
11   50
12   51
13   17
14   13
15   16
16   45
17   20
18   29
19   24
20   27
21   27
22   23
23   39
24   44
25   12
26   10
27   15
28   19
29   31
30   10
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

     시군구 계약구분  비율
0    가평군  일반용  46
1    고양시  일반용  44
2    과천시  일반용  58
3    광명시  일반용  37
4    광주시  일반용  25
5    구리시  일반용  49
6    군포시  일반용  27
7    김포시  일반용  18
8   남양주시  일반용  31
9   동두천시  일반용  35
10   부천시  일반용  31
11   성남시  일반용  50
12   수원시  일반용  51
13   시흥시  일반용  17
14   안산시  일반용  13
15   안성시  일반용  16
16   안양시  일반용  45
17   양주시  일반용  20
18   양평군  일반용  29
19   여주시  일반용  24
20   연천군  일반용  27
21   오산시  일반용  27
22   용인시  일반용  23
23   의왕시  일반용  39
24  의정부시  일반용  44
25   이천시  일반용  12
26   파주시  일반용  10
27   평택시  일반용  15
28   포천시  일반용  19
29   하남시  일반용  31
30   화성시  일반용  10

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201407-201412  경기도  가평군  일반용    9105   126843876  46
1   201407-201412  경기도  가평군   합계    9753   277384067 NaN
2   201407-201412  경기도  고양시  일반용   38499   936653952  44
3   201407-201412  경기도  고양시   합계   35607  2122706480 NaN
4   201407-201412  경기도  과천시  일반용    2211   113854952  58
..            ...  ...  ...  ...     ...         ...  ..
56  201407-201412  경기도  포천시   합계   17567  1157994461 NaN
59  201407-201412  경기도  하남시  일반용   12233   163667131  31
58  201407-201412  경기도  하남시   합계    7637   526629823 NaN
60  201407-201412  경기도  화성시  일반용   33022   722470190  10
61  201407-201412  경기도  화성시   합계   33157  7184071063 NaN

[62 rows x 7 columns]

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1407-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)