In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('강원도_계약종별 전력사용량 월별_14하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 강원도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2014년 07 월 ~ 2014년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,강원도,전체(시 / 군 / 구),주택용,"525,959","151,437,109","17,356,531,828",114.6
4,201407,강원도,전체(시 / 군 / 구),일반용,"131,800","313,603,314","46,402,023,301",148.0
...,...,...,...,...,...,...,...,...
907,201412,강원도,횡성군,산업용,547,"13,934,721","1,835,744,578",131.7
908,201412,강원도,횡성군,심 야,"6,547","17,467,246","1,308,872,325",74.9
909,201412,강원도,횡성군,일반용,"4,640","15,702,711","2,006,474,348",127.8
910,201412,강원도,횡성군,주택용,"20,479","4,739,840","603,631,204",127.4
911,201412,강원도,횡성군,합계,"46,462","58,828,335","6,201,597,738",105.4

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,강원도,전체(시 / 군 / 구),주택용,"525,959","151,437,109","17,356,531,828",114.6
4,201407,강원도,전체(시 / 군 / 구),일반용,"131,800","313,603,314","46,402,023,301",148.0
5,201407,강원도,전체(시 / 군 / 구),교육용,"1,038","20,447,431","2,844,580,783",139.1
6,201407,강원도,전체(시 / 군 / 구),산업용,"12,040","605,010,420","70,060,007,675",115.8
...,...,...,...,...,...,...,...,...
907,201412,강원도,횡성군,산업용,547,"13,934,721","1,835,744,578",131.7
908,201412,강원도,횡성군,심 야,"6,547","17,467,246","1,308,872,325",74.9
909,201412,강원도,횡성군,일반용,"4,640","15,702,711","2,006,474,348",127.8
910,201412,강원도,횡성군,주택용,"20,479","4,739,840","603,631,204",127.4
911,201412,강원도,횡성군,합계,"46,462","58,828,335","6,201,597,738",105.4

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,강원도,전체(시 / 군 / 구),주택용,"525,959","151,437,109","17,356,531,828",114.6
4,201407,강원도,전체(시 / 군 / 구),일반용,"131,800","313,603,314","46,402,023,301",148.0
5,201407,강원도,전체(시 / 군 / 구),교육용,"1,038","20,447,431","2,844,580,783",139.1
6,201407,강원도,전체(시 / 군 / 구),산업용,"12,040","605,010,420","70,060,007,675",115.8
7,201407,강원도,전체(시 / 군 / 구),농사용,"79,908","38,174,129","1,893,043,876",49.6
...,...,...,...,...,...,...,...,...
907,201412,강원도,횡성군,산업용,547,"13,934,721","1,835,744,578",131.7
908,201412,강원도,횡성군,심 야,"6,547","17,467,246","1,308,872,325",74.9
909,201412,강원도,횡성군,일반용,"4,640","15,702,711","2,006,474,348",127.8
910,201412,강원도,횡성군,주택용,"20,479","4,739,840","603,631,204",127.4
911,201412,강원도,횡성군,합계,"46,462","58,828,335","6,201,597,738",105.4

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,강원도,전체(시 / 군 / 구),주택용,"525,959","151,437,109","17,356,531,828",114.6
4,201407,강원도,전체(시 / 군 / 구),일반용,"131,800","313,603,314","46,402,023,301",148.0
5,201407,강원도,전체(시 / 군 / 구),교육용,"1,038","20,447,431","2,844,580,783",139.1
6,201407,강원도,전체(시 / 군 / 구),산업용,"12,040","605,010,420","70,060,007,675",115.8
7,201407,강원도,전체(시 / 군 / 구),농사용,"79,908","38,174,129","1,893,043,876",49.6
8,201407,강원도,전체(시 / 군 / 구),가로등,"95,955","12,512,816","1,526,111,287",122.0
9,201407,강원도,전체(시 / 군 / 구),심 야,"95,270","46,085,957","2,550,867,474",55.4
10,201408,강원도,전체(시 / 군 / 구),주택용,"527,076","168,072,589","21,125,747,834",125.7
11,201408,강원도,전체(시 / 군 / 구),일반용,"132,531","348,756,787","50,711,149,002",145.4
12,201408,강원도,전체(시 / 군 / 구),교육용,"1,037","19,549,096","2,752,401,986",140.8
13,201408,강원도,전체(시 / 군 / 구),산업용,"12,107","577,545,076","64,875,891,439",112.3
14,201408,강원도,전체(시 / 군 / 구),농사용,"80,587","46,934,390","2,286,133,051",48.7
15,201408,강원도,전체(시 / 군 / 구),가로등,"96,209","13,233,729","1,625,335,715",122.8
16,201408,강원도,전체(시 / 군 / 구),심 야,"95,225","40,785,147","2,276,177,472",55.8
17,201409,강원도,전체(시 / 군 / 구),주택용,"527,846","158,446,027","18,709,516,512",118.1
18,201409,강원도,전체(시 / 군 / 구),일반용,"132,772","304,416,515","39,731,678,751",130.5
19,201409,강원도,전체(시 / 군 / 구),교육용,"1,038","18,891,266","2,379,152,855",125.9
20,201409,강원도,전체(시 / 군 / 구),산업용,"12,138","584,131,577","54,356,357,389",93.1
21,201409,강원도,전체(시 / 군 / 구),농사용,"81,226","50,204,481","2,461,183,847",49.0
22,201409,강원도,전체(시 / 군 / 구),가로등,"96,464","13,857,317","1,587,458,259",114.6
23,201409,강원도,전체(시 / 군 / 구),심 야,"95,186","49,721,885","2,760,277,120",55.5
24,201410,강원도,전체(시 / 군 / 구),주택용,"528,726","151,339,153","17,129,017,977",113.2
25,201410,강원도,전체(시 / 군 / 구),일반용,"132,783","283,986,579","33,383,330,284",117.6
26,201410,강원도,전체(시 / 군 / 구),교육용,"1,038","18,627,359","2,050,212,761",110.1
27,201410,강원도,전체(시 / 군 / 구),산업용,"12,157","631,119,925","56,999,807,710",90.3
28,201410,강원도,전체(시 / 군 / 구),농사용,"81,523","46,743,596","2,315,693,393",49.5
29,201410,강원도,전체(시 / 군 / 구),가로등,"96,484","14,577,852","1,598,087,139",109.6
30,201410,강원도,전체(시 / 군 / 구),심 야,"95,167","79,929,464","4,381,121,611",54.8
31,201411,강원도,전체(시 / 군 / 구),주택용,"529,694","163,742,238","19,721,635,150",120.4
32,201411,강원도,전체(시 / 군 / 구),일반용,"133,027","313,076,790","40,133,015,525",128.2
33,201411,강원도,전체(시 / 군 / 구),교육용,"1,042","23,538,361","2,618,777,888",111.3
34,201411,강원도,전체(시 / 군 / 구),산업용,"12,173","620,661,127","69,300,416,819",111.7
35,201411,강원도,전체(시 / 군 / 구),농사용,"103,382","61,499,735","2,651,711,063",43.1
36,201411,강원도,전체(시 / 군 / 구),가로등,"96,681","15,593,241","1,662,860,052",106.6
37,201411,강원도,전체(시 / 군 / 구),심 야,"95,172","157,028,112","9,925,043,079",63.2
38,201412,강원도,전체(시 / 군 / 구),주택용,"530,653","170,946,320","21,479,610,370",125.7
39,201412,강원도,전체(시 / 군 / 구),일반용,"133,452","387,233,733","51,191,559,057",132.2
40,201412,강원도,전체(시 / 군 / 구),교육용,"1,043","35,341,390","3,873,357,089",109.6
41,201412,강원도,전체(시 / 군 / 구),산업용,"12,186","616,100,631","70,174,293,947",113.9
42,201412,강원도,전체(시 / 군 / 구),농사용,"81,542","43,748,215","2,186,221,480",50.0
43,201412,강원도,전체(시 / 군 / 구),가로등,"96,926","15,943,121","1,595,212,727",100.1
44,201412,강원도,전체(시 / 군 / 구),심 야,"95,144","242,860,737","18,232,433,004",75.1
45,합계,합계,합계,합계,"5,703,407","7,675,454,737","842,875,045,581",109.8

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_20616\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월   시구 계약구분   고객호수(호)      사용량(kWh)
4   201407  강원도  일반용  131,800   313,603,314
11  201408  강원도  일반용  132,531   348,756,787
18  201409  강원도  일반용  132,772   304,416,515
25  201410  강원도  일반용  132,783   283,986,579
32  201411  강원도  일반용  133,027   313,076,790
39  201412  강원도  일반용  133,452   387,233,733

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201407  강원도  강릉시  일반용  17,524   36,983,966
197  201408  강원도  강릉시  일반용  17,640   42,575,202
341  201409  강원도  강릉시  일반용  17,683   37,380,029
485  201410  강원도  강릉시  일반용  17,738   33,831,138
629  201411  강원도  강릉시  일반용  17,746   35,594,943
..      ...  ...  ...  ...      ...          ...
333  201408  강원도  횡성군  일반용   4,568   10,632,247
477  201409  강원도  횡성군  일반용   4,594    9,350,948
621  201410  강원도  횡성군  일반용   4,604    9,129,146
765  201411  강원도  횡성군  일반용   4,603   11,009,090
909  201412  강원도  횡성군  일반용   4,640   15,702,711

[108 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'강원도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강릉시',
 '고성군',
 '동해시',
 '삼척시',
 '속초시',
 '양구군',
 '양양군',
 '영월군',
 '원주시',
 '인제군',
 '정선군',
 '철원군',
 '춘천시',
 '태백시',
 '평창군',
 '홍천군',
 '화천군',
 '횡성군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월   시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201407  강원도  강릉시   합계  121,146   147,846,891
199  201408  강원도  강릉시   합계  121,372   155,493,393
343  201409  강원도  강릉시   합계  121,563   151,188,847
487  201410  강원도  강릉시   합계  121,747   153,466,396
631  201411  강원도  강릉시   합계  122,123   164,567,556
..      ...  ...  ...  ...       ...           ...
335  201408  강원도  횡성군   합계   46,095    37,138,303
479  201409  강원도  횡성군   합계   46,188    35,426,136
623  201410  강원도  횡성군   합계   46,285    36,698,347
767  201411  강원도  횡성군   합계   48,269    47,229,991
911  201412  강원도  횡성군   합계   46,462    58,828,335

[108 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[147846891, 155493393, 151188847, 153466396, 164567556, 171482068]
[20041222, 21237872, 20326639, 20127255, 22880007, 26155420]
[256092081, 241292038, 251995627, 267823110, 256246978, 264528555]
[97182121, 101332913, 95050362, 101317630, 106082578, 109561957]
[33409666, 37642608, 34019909, 32881554, 35959898, 41282087]
[11943239, 12997160, 12765069, 13541842, 19617178, 21540644]
[18219819, 19997385, 19108465, 19004283, 21685404, 24301478]
[82522136, 82097320, 79269737, 90731832, 95597685, 92777504]
[164015885, 166298214, 156855560, 158158681, 183277972, 218340139]
[19378534, 20345141, 20556588, 21980231, 26824556, 32718968]
[41893941, 41232523, 43919318, 47778951, 51603775, 62860746]
[27811092, 30393242, 28268072, 30490352, 43914489, 47378091]
[113655338, 120921258, 110879231, 106962436, 124825738, 148078951]
[23211811, 23521388, 23642411, 24508020, 27905215, 31246174]
[35627888, 38547779, 36732614, 40477243, 51471611, 68019252]
[44825625, 48598632, 44579889, 45019455, 56034867, 69457828]
[14130057, 15789645, 15084594, 15356310, 19414106, 23615950]
[35463830, 37138303, 35426136, 36698347, 47229991, 58828335]
강원도 지역별 합계 :  [944045151, 130768415, 1537978389, 610527561, 215195722, 92405132, 122316834, 522996214, 1046946451, 141804018, 289289254, 208255338, 725322952, 154035019, 270876387, 308516296, 103390662, 250784942]
강원도 고객호수 평균:  [20279, 4448, 7677, 8304, 6257, 3450, 4604, 6203, 23079, 5290, 5984, 6698, 21765, 4584, 7763, 10652, 3626, 7757]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_20616\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201407  강원도  강릉시   합계  121,146   147,846,891
1           201408  강원도  강릉시   합계  121,372   155,493,393
2           201409  강원도  강릉시   합계  121,563   151,188,847
3           201410  강원도  강릉시   합계  121,747   153,466,396
4           201411  강원도  강릉시   합계  122,123   164,567,556
..             ...  ...  ...  ...       ...           ...
121  201407-201412  강원도  태백시   합계      4584     154035019
122  201407-201412  강원도  평창군   합계      7763     270876387
123  201407-201412  강원도  홍천군   합계     10652     308516296
124  201407-201412  강원도  화천군   합계      3626     103390662
125  201407-201412  강원도  횡성군   합계      7757     250784942

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201407-201412']
Hap

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201407-201412  강원도  강릉시   합계   20279   944045151
109  201407-201412  강원도  고성군   합계    4448   130768415
110  201407-201412  강원도  동해시   합계    7677  1537978389
111  201407-201412  강원도  삼척시   합계    8304   610527561
112  201407-201412  강원도  속초시   합계    6257   215195722
113  201407-201412  강원도  양구군   합계    3450    92405132
114  201407-201412  강원도  양양군   합계    4604   122316834
115  201407-201412  강원도  영월군   합계    6203   522996214
116  201407-201412  강원도  원주시   합계   23079  1046946451
117  201407-201412  강원도  인제군   합계    5290   141804018
118  201407-201412  강원도  정선군   합계    5984   289289254
119  201407-201412  강원도  철원군   합계    6698   208255338
120  201407-201412  강원도  춘천시   합계   21765   725322952
121  201407-201412  강원도  태백시   합계    4584   154035019
122  201407-201412  강원도  평창군   합계    7763   270876387
123  201407-201412  강원도  홍천군   합계   10652   308516296
124  201407-201412  강원도  화천군   합계    3626   103390662
125  201407-201412  강원도  횡성군   합계    7757   250784942

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201407  강원도  강릉시  일반용  17,524   36,983,966
197  201408  강원도  강릉시  일반용  17,640   42,575,202
341  201409  강원도  강릉시  일반용  17,683   37,380,029
485  201410  강원도  강릉시  일반용  17,738   33,831,138
629  201411  강원도  강릉시  일반용  17,746   35,594,943
..      ...  ...  ...  ...      ...          ...
333  201408  강원도  횡성군  일반용   4,568   10,632,247
477  201409  강원도  횡성군  일반용   4,594    9,350,948
621  201410  강원도  횡성군  일반용   4,604    9,129,146
765  201411  강원도  횡성군  일반용   4,603   11,009,090
909  201412  강원도  횡성군  일반용   4,640   15,702,711

[108 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[36983966, 42575202, 37380029, 33831138, 35594943, 40890203]
[9445793, 10774901, 9471139, 8522554, 8893723, 10266415]
[15320304, 17283644, 15513874, 14561892, 15617640, 18006188]
[11654624, 13426905, 11934557, 11844249, 12873451, 15224652]
[18736607, 22252907, 18680489, 17178128, 17707407, 20228192]
[5175667, 5875466, 5318336, 5168977, 6171447, 7356931]
[8675581, 10355149, 8891783, 8093168, 8669552, 9582437]
[5732535, 6618585, 5792700, 5301601, 5804520, 6723344]
[54861383, 58952476, 51703683, 46530039, 51089747, 63870285]
[9873281, 10478992, 9318564, 9201811, 10531198, 12620943]
[13426820, 14403328, 12434635, 12499739, 14453388, 21777404]
[10670361, 11685934, 10423938, 10023710, 11911500, 14970214]
[53786588, 58320911, 51367085, 46267964, 49203177, 57879504]
[6319561, 7012588, 6551969, 6396234, 7074834, 8250748]
[16840068, 18672886, 15728600, 16699053, 20903599, 31001135]
[19327186, 21107092, 17008604, 15578230, 17453021, 23129991]
[7329184, 8327574, 7545582, 7158946, 8114553, 9752436]
[9443805, 10632247, 9350948, 9129146, 11009090, 15702711]
강원도 지역별 일반용 합계 :  [227255481, 57374525, 96303542, 76958438, 114783730, 35066824, 54267670, 35973285, 327007613, 62024789, 88995314, 69685657, 316825229, 41605934, 119845341, 113604124, 48228275, 65267947]
강원도 고객호수 평균:  [17689, 3648, 6693, 5934, 7555, 2359, 3886, 3975, 22536, 4265, 4855, 4682, 19587, 4052, 5802, 7605, 3004, 4590]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_20616\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_20616\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201407  강원도  강릉시  일반용  17,524   36,983,966
1           201408  강원도  강릉시  일반용  17,640   42,575,202
2           201409  강원도  강릉시  일반용  17,683   37,380,029
3           201410  강원도  강릉시  일반용  17,738   33,831,138
4           201411  강원도  강릉시  일반용  17,746   35,594,943
..             ...  ...  ...  ...      ...          ...
121  201407-201412  강원도  태백시  일반용     4052     41605934
122  201407-201412  강원도  평창군  일반용     5802    119845341
123  201407-201412  강원도  홍천군  일반용     7605    113604124
124  201407-201412  강원도  화천군  일반용     3004     48228275
125  201407-201412  강원도  횡성군  일반용     4590     65267947

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201407-201412']
GyeonGiHap2

                년월   시구  시군구 계약구분 고객호수(호)   사용량(kWh)
108  201407-201412  강원도  강릉시  일반용   17689  227255481
109  201407-201412  강원도  고성군  일반용    3648   57374525
110  201407-201412  강원도  동해시  일반용    6693   96303542
111  201407-201412  강원도  삼척시  일반용    5934   76958438
112  201407-201412  강원도  속초시  일반용    7555  114783730
113  201407-201412  강원도  양구군  일반용    2359   35066824
114  201407-201412  강원도  양양군  일반용    3886   54267670
115  201407-201412  강원도  영월군  일반용    3975   35973285
116  201407-201412  강원도  원주시  일반용   22536  327007613
117  201407-201412  강원도  인제군  일반용    4265   62024789
118  201407-201412  강원도  정선군  일반용    4855   88995314
119  201407-201412  강원도  철원군  일반용    4682   69685657
120  201407-201412  강원도  춘천시  일반용   19587  316825229
121  201407-201412  강원도  태백시  일반용    4052   41605934
122  201407-201412  강원도  평창군  일반용    5802  119845341
123  201407-201412  강원도  홍천군  일반용    7605  113604124
124  201407-201412  강원도  화천군  일반용    3004   48228275
125  201407-201412  강원도  횡성군  일반용    4590   65267947

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201407-201412  강원도  강릉시  일반용   17689   227255481
108  201407-201412  강원도  강릉시   합계   20279   944045151
109  201407-201412  강원도  고성군  일반용    3648    57374525
109  201407-201412  강원도  고성군   합계    4448   130768415
110  201407-201412  강원도  동해시  일반용    6693    96303542
110  201407-201412  강원도  동해시   합계    7677  1537978389
111  201407-201412  강원도  삼척시   합계    8304   610527561
111  201407-201412  강원도  삼척시  일반용    5934    76958438
112  201407-201412  강원도  속초시   합계    6257   215195722
112  201407-201412  강원도  속초시  일반용    7555   114783730
113  201407-201412  강원도  양구군  일반용    2359    35066824
113  201407-201412  강원도  양구군   합계    3450    92405132
114  201407-201412  강원도  양양군   합계    4604   122316834
114  201407-201412  강원도  양양군  일반용    3886    54267670
115  201407-201412  강원도  영월군  일반용    3975    35973285
115  201407-201412  강원도  영월군   합계    6203   522996214
116  201407-201412  강원도  원주시  일반용   22536   327007613
116  201407-201412  강원도  원주시   합계   23079  1046946451
117  201407-201412  강원도  인제군  일반용    4265    62024789
117  201407-201412  강원도  인제군   합계    5290   141804018
118  201407-201412  강원도  정선군   합계    5984   289289254
118  201407-201412  강원도  정선군  일반용    4855    88995314
119  201407-201412  강원도  철원군   합계    6698   208255338
119  201407-201412  강원도  철원군  일반용    4682    69685657
120  201407-201412  강원도  춘천시  일반용   19587   316825229
120  201407-201412  강원도  춘천시   합계   21765   725322952
121  201407-201412  강원도  태백시   합계    4584   154035019
121  201407-201412  강원도  태백시  일반용    4052    41605934
122  201407-201412  강원도  평창군   합계    7763   270876387
122  201407-201412  강원도  평창군  일반용    5802   119845341
123  201407-201412  강원도  홍천군   합계   10652   308516296
123  201407-201412  강원도  홍천군  일반용    7605   113604124
124  201407-201412  강원도  화천군   합계    3626   103390662
124  201407-201412  강원도  화천군  일반용    3004    48228275
125  201407-201412  강원도  횡성군  일반용    4590    65267947
125  201407-201412  강원도  횡성군   합계    7757   250784942

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[227255481,
 57374525,
 96303542,
 76958438,
 114783730,
 35066824,
 54267670,
 35973285,
 327007613,
 62024789,
 88995314,
 69685657,
 316825229,
 41605934,
 119845341,
 113604124,
 48228275,
 65267947]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[944045151,
 130768415,
 1537978389,
 610527561,
 215195722,
 92405132,
 122316834,
 522996214,
 1046946451,
 141804018,
 289289254,
 208255338,
 725322952,
 154035019,
 270876387,
 308516296,
 103390662,
 250784942]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[24.07, 43.87, 6.26, 12.61, 53.34, 37.95, 44.37, 6.88, 31.23, 43.74, 30.76, 33.46, 43.68, 27.01, 44.24, 36.82, 46.65, 26.03]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    24
1    44
2     6
3    13
4    53
5    38
6    44
7     7
8    31
9    44
10   31
11   33
12   44
13   27
14   44
15   37
16   47
17   26
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   강릉시  일반용  24
1   고성군  일반용  44
2   동해시  일반용   6
3   삼척시  일반용  13
4   속초시  일반용  53
5   양구군  일반용  38
6   양양군  일반용  44
7   영월군  일반용   7
8   원주시  일반용  31
9   인제군  일반용  44
10  정선군  일반용  31
11  철원군  일반용  33
12  춘천시  일반용  44
13  태백시  일반용  27
14  평창군  일반용  44
15  홍천군  일반용  37
16  화천군  일반용  47
17  횡성군  일반용  26

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201407-201412  강원도  강릉시  일반용   17689   227255481  24
1   201407-201412  강원도  강릉시   합계   20279   944045151 NaN
2   201407-201412  강원도  고성군  일반용    3648    57374525  44
3   201407-201412  강원도  고성군   합계    4448   130768415 NaN
4   201407-201412  강원도  동해시  일반용    6693    96303542   6
5   201407-201412  강원도  동해시   합계    7677  1537978389 NaN
7   201407-201412  강원도  삼척시  일반용    5934    76958438  13
6   201407-201412  강원도  삼척시   합계    8304   610527561 NaN
9   201407-201412  강원도  속초시  일반용    7555   114783730  53
8   201407-201412  강원도  속초시   합계    6257   215195722 NaN
10  201407-201412  강원도  양구군  일반용    2359    35066824  38
11  201407-201412  강원도  양구군   합계    3450    92405132 NaN
13  201407-201412  강원도  양양군  일반용    3886    54267670  44
12  201407-201412  강원도  양양군   합계    4604   122316834 NaN
14  201407-201412  강원도  영월군  일반용    3975    35973285   7
15  201407-201412  강원도  영월군   합계    6203   522996214 NaN
16  201407-201412  강원도  원주시  일반용   22536   327007613  31
17  201407-201412  강원도  원주시   합계   23079  1046946451 NaN
18  201407-201412  강원도  인제군  일반용    4265    62024789  44
19  201407-201412  강원도  인제군   합계    5290   141804018 NaN
21  201407-201412  강원도  정선군  일반용    4855    88995314  31
20  201407-201412  강원도  정선군   합계    5984   289289254 NaN
23  201407-201412  강원도  철원군  일반용    4682    69685657  33
22  201407-201412  강원도  철원군   합계    6698   208255338 NaN
24  201407-201412  강원도  춘천시  일반용   19587   316825229  44
25  201407-201412  강원도  춘천시   합계   21765   725322952 NaN
27  201407-201412  강원도  태백시  일반용    4052    41605934  27
26  201407-201412  강원도  태백시   합계    4584   154035019 NaN
29  201407-201412  강원도  평창군  일반용    5802   119845341  44
28  201407-201412  강원도  평창군   합계    7763   270876387 NaN
31  201407-201412  강원도  홍천군  일반용    7605   113604124  37
30  201407-201412  강원도  홍천군   합계   10652   308516296 NaN
33  201407-201412  강원도  화천군  일반용    3004    48228275  47
32  201407-201412  강원도  화천군   합계    3626   103390662 NaN
34  201407-201412  강원도  횡성군  일반용    4590    65267947  26
35  201407-201412  강원도  횡성군   합계    7757   250784942 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1407-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)